### ISSUE TITLE
use of data-association-insertion-traversal option causes add link to fail without error

### ISSUE THREAD

**Issue by shaundrong** [nathanvda/cocoon#102]
using the data-association-insertion-traversal option on link_to_add_association seems to cause the link to not function. I've tried it setting as a html option param and via jquery with the data set function,  and both seem to cause the link to fail. Link functions correctly when it is removed. This seems to be a bug introduced with 1.1.0 as the same link functioned correctly in the previous release.

**Comment by py523** [comment]
I'm having the same problem too. I want to select the closest node (because I have a 3-level form) but 'association-insertion-traversal' doesn't seem to work at all. Any ideas?

**Comment by dskvr** [comment]
Has this been fixed?

**Comment by ExClouds** [comment]
This is added in *2012*. How come it's not fixed yet?

**Comment by nathanvda** [comment]
You are right! Outrageous! Apparently it is easier to just complain about apparent bugs and _lack of service_ then to actually fix this.

It is not fixed, for several reasons: 

1) is it really broken? Note that if the selector does not find anything, it will seem broken, but the code is working. This does make it really hard to debug.
2) I never use this option, and I frankly do not like because it is not very intuitive. Traversal, from where? I once started a rewrite of this part, but then life and work happened, and I do not need it. So why bother?
3) This is open source, and apparently nobody really felt the urge to improve this for free

**Comment by nathanvda** [comment]
Since #355 offers a very versatile and imho more intuitive alternative this can be closed.
