### ISSUE TITLE
Abort if callback returns false

### ISSUE THREAD

**Issue by rurounijones** [nathanvda/cocoon#113]
I would like to be able to limit the number of times a user can add a particular child. My thought would be that if a cocoon:before-insert or a cocoon:before-remove callback returns false then the action is aborted.

For example (CoffeeScript) being able to do something like this would be nice:

``` coffee
  $("#dockets").bind "cocoon:before-insert", (e, inserted_item) ->
    if $("#dockets .nested-fields").length >= 10
      return false
```

**Comment by cannikin** [comment]
I have this use case as well, although rather than limiting the number of times a user can do something, I'm trying to prevent them from building duplicate records. 

So they add the label "food" to a list of tags, then try to type in "food" again a second time. If I detect that "food" record already exists in the `cocoon:before-insert` event I can prevent it from being added again. Gonna try @yoavmatchulsky's fork!

**Comment by nathanvda** [comment]
Mmmm the cocoon:insert is before inserting an empty partial (before any user interaction, like typing content), so imho you can only remove duplicates in the controller, or before submitting it to the server. So I would add some kind of client validation instead, showing no duplicate is allowed.
