### ISSUE TITLE
when work cocoon:before-remove, cocoon:after-remove ?

### ISSUE THREAD

**Issue by patie** [nathanvda/cocoon#167]
im tryiing events

```
$(document).ready(function () {

    $('#items')
        .on('cocoon:before-insert', function () {
            console.log('before insert');
        })
        .on('cocoon:after-insert', '#items', function () {
            console.log('after insert');
        })
        .on("cocoon:before-remove", '#items', function () {
            console.log('before remove');
        })
        .on("cocoon:after-remove", function () {
            console.log('after remove');
        });

});
```

cocoon:before-insert
cocoon:after-insert
works ok

cocoon:before-remove
cocoon:after-remove
dont work

remove events works only on existing items - in update? its not "live" right? because im trying it during adding new item

thanks

**Comment by smartmall** [comment]
Can I assign a id for a repeating divs ?

**Comment by smartmall** [comment]
I just want to identify repeating divs separately , want to add unique id for each main div .any help will appreciate

**Comment by Mirv** [comment]
@smartmall friendly suggestion for using github ...proper github etiquette would be to start a new issue & link back to this one if it's related.   

A path you could pursue for your problem ...

Use jquery's custom callbacks (described here ... https://github.com/nathanvda/cocoon#callbacks-upon-insert-and-remove-of-items) & generate an ID of your choice.

I have a feeling that generating the ID, storing & recalling the ID will be most of your problem as the jquery to add an html element is easy.

Something like https://api.jquery.com/add/ or `$('selector').attr( 'id', 'yourId' );` ...  something like here would probably work - but you will need to limit the scope so it only targets the <first / last> div of that name you added.  I say < first / last > because cocoon has an option to change where you place the most recently added element.

**Comment by smartmall** [comment]
Thank you very much for replying me .The Problem is Use jquery's custom callbacks, is not working for me , 
![divs](https://cloud.githubusercontent.com/assets/26533269/25262536/58761e56-2676-11e7-99c9-7d217e62ce89.PNG)

this is what i am going to do , as you can see, i am repeating email field and that div selecting part, so i just want collect separately  selected divs for each repeating   part, and send them to controller . here is my javascript for select 

    $(document).on('click', '.myDivs', function () {
        $(this).toggleClass('selected');

        var selectedRoles = $('.selected').map(function() {
            var divId = this.id;
            var parentDivId = $(this).parents(".repetediv")[0].id;
            console.log("pA "+parentDivId);
            //var roleNames = $('#'+divId+' h5').text();
            var roleNames = $('#'+parentDivId).find('#'+divId+' h5').text();
            return roleNames;
        }).get();

        console.log(selectedRoles);
        var top = $(this).parents(".repetediv")[0].getElementsByClassName("rolefield")[0].id;
        console.log('top '+top);
        document.getElementById(top).value = selectedRoles;
        // $("#"+top).val(selectedRoles);
    }); 


so its giving all the divs that have been selected , i cant group them , Thank you again for reply me

**Comment by smartmall** [comment]
any help will appreciate

**Comment by nathanvda** [comment]
As @Mirv said: it is not proper etiquette to hijack an old (solved!) issue to try to get help for a seemingly unrelated question. 

I also do not understand: the code you are showing and your original question do not directly refer to cocoon. Your problem does not appear to be with cocoon callbacks at all, but with jquery/selectors, right? 

I urge you to do one of two things: 

* if your question _is_ related to cocoon, and you cannot get nested forms to work, start a new issue, with it's own title and a clear explanation what you are trying to achieve (with cocoon) and what is stopping you 
* if your question is much more generic, basic html/css/jquery which you encountered while doing something with cocoon, please ask on stackoverflow.com, there a load of specialists in all fields that will be able to help you a lot quicker. You can also post the link to the question here.

**Comment by smartmall** [comment]
Oh sorry and i made a new issue too, i will explain it since you have replied here. I am using cocoon to generate above part , that i have send a screen shot here. As you can see there are custom made div selector. since cocoon repeating  those main container div I cant group selected divs for one part. That's why i want to generate a id for main container div, for identify separately . Is there any way to generate id for divs also in cocoon ? I am new to ruby. sorry for that. This is the link to new issue.  Thank you for replying me.

https://github.com/nathanvda/cocoon/issues/419
