### ISSUE TITLE
Problems with link_to_remove_association

### ISSUE THREAD

**Issue by mcpenchel** [nathanvda/cocoon#212]
Hi,

I'm having two problems with this feature. The first one is that when I create N nested objects in the form and try to delete them before submitting, the controller ignores the first one. Example: I clicked in "Adicionar pessoa" 5 times, chose a nationality for each and then decided to remove all of them, clicking in their respective "Remover pessoa" buttons. The first one will not be removed, it will be saved.

The second issue I'm having is that when I click the "Remover pessoa" button, the object stays in the form. It's like nothing happens, but the controller nonetheless understands and removes it after the submit.

Here's my simplified code:
apartments/_form.html.erb: https://gist.github.com/mcpenchel/9eb1740d525a6b84b686
apartments/_person_fields.html.erb: https://gist.github.com/mcpenchel/aa7232d134751522c0b1
application.js: https://gist.github.com/mcpenchel/71c5f3ad4d4cf6e7b8d0

Hope you can help.

Cheers,
Matheus.

**Comment by bswinnerton** [comment]
Not to re-open an old issue, but I just ran into this issue as well. It would be very helpful if somewhere in the documentation in _big_ **bold** letters it was stated that the partial has to be surrounded by `<div class="nested-fields"></div>`.

**Comment by nathanvda** [comment]
And that is not obvious from the examples? Is reading haml a problem for you? There is a wiki page with the [ERB examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples).


Maybe it is not clear enough. I guessed if people followed the examples, it would be clear. 
Also in the documentation for [link_to_remove_association](https://github.com/nathanvda/cocoon#link_to_remove_association) I write it is possible to overrule the wrapper-class. But I can imagine it is a lot of documentation to chew through at the beginning.

**Comment by idiazroncero** [comment]
First of all, @nathanvda), thanks for your amazing work. Cocoon is a real life-saver.

I also ran into this issue, with link_to_remove_association apparently not working at all just because I didn't understood '.nested-fields' to be compulsory, but an optional class name. The docs' examples (https://github.com/nathanvda/cocoon#standard-rails-forms) use some evident "placeholder" classes and IDs (`.fields`, `#tasks`, `.links`) so I assumed it was safe to alter those values to fit my needs... including `.nested-fields`.

Maybe we should find an standard way to clarify, when documenting examples, which HTML class names and IDs are just mere placeholders and which ones are actually expected to exist, to respect a given naming convention and/or to be overriden.

(Or maybe that convention already exists, and I didn't realize. I'm new to Rails and GitHub)

**Comment by nathanvda** [comment]
It is already explicitly stated twice in the readme :) But: not close to the examples. I see what you mean, and indeed that is good suggestion, only I have no idea such a standard way exists. 

I did my best to make the documentation as complete as possible, so the information is there. But it is hard to see which is crucial and which is extra. I still should add some kind of FAQ page because a lot of problems are recurring.

**Comment by Grantismo** [comment]
I too ran into this oversight. Maybe just adding a little explanatory blurb to the documentation would help?

"And in our _task_fields partial we'd write: (note that the ".nested-fields" div is required)"
