### ISSUE TITLE
Add association programmatically?

### ISSUE THREAD

**Issue by howells** [nathanvda/cocoon#259]
I could be missing something obvious here, but how might I add an association programmatically rather than on a click event? (In my case I am prepopulating data and need to be able to add multiple associations without the user having to do anything).

**Comment by simi** [comment]
You mean before page is rendered?

**Comment by howells** [comment]
I mean, essentially the equivalent of

    $('.add_fields[data-association=twitter_account]').trigger('click')

but that's a bit ghetto!

**Comment by simi** [comment]
There's no way how to do that.

https://github.com/nathanvda/cocoon/blob/master/app/assets/javascripts/cocoon.js#L17

It will be nice refactored to use binds just to attach custom functions, so you can reuse it manually when you'll need.

@nathanvda do you agree?

**Comment by nathanvda** [comment]
I am currently refactoring the js. Not sure if that will be possible though. @howells Could you explain a bit more in detail what you are trying to achieve?

Prepopulating from the server is pretty clean. Prepopulating from the client could be easy, if you just need to trigger the click function. But if you need to set specific values, then it gets a little complicated Because the default values/partial is of course rendered on the server, and in that case I am not sure if cocoon is the best solution for you. You could use the callbacks to set some values, but this would get hairy fast imho.

**Comment by howells** [comment]
@nathanvda I suppose mine is an edge case. Basically I'm pre-populating a form via data from an ajax call, and where there are multiple values for a given association I want to be able to add the associations and populate the values without the user having to do anything. But yes, in this case I suppose a click trigger is good enough.

**Comment by nathanvda** [comment]
And did you consider rendering the complete form server-side? Not really sure if it applies in your case, but prepopulating a form via ajax, sounds like you might just as well render it server-side and replace completely.

**Comment by simi** [comment]
@nathanvda is there any public preview (more like "technological preview")?

**Comment by howells** [comment]
@nathanvda Considered it but ultimately I wanted one less step in the process without having the user to do a lookup, save the model, and then edit the model, but might return to that as does seems sensible. Congrats on an amazing gem btw, so useful.
@simi not yet unfortunately!

**Comment by nathanvda** [comment]
Closed due to inactivity.

**Comment by daneelliotthamilton** [comment]
I'm thinking that it could be added programmatically in a scenario used in conjunction with jquery file upload, where if the user drags a file into the dropzone, an associated nested field is added, with programmatically filled fields. If multiple files are added, multiple nested fields are added.

**Comment by nathanvda** [comment]
@daneelliotthamilton for adding multiple attachments I personally use [dropzone ](http://www.dropzonejs.com/) in that specific case, which is awesome BTW 👍 But it is not identical indeed, since it automatically uploads the files, and allows no extra fields to be added. On/after drop, you could send the `click` event to the button, which does sound a bit lame, but works?
