### ISSUE TITLE
link_to_remove_association _destroy field still 'true' if validation fails

### ISSUE THREAD

**Issue by ryan2johnson9** [nathanvda/cocoon#260]
I edit my model and destroy one of the nested models via link_to_remove_assocation.

I have a validation in the model that does not permit this in certain circumstances and adds an error to this nested resource.

The edit page reloads, and I can see the nested resource which I had attempted to destroy with the error message displayed.

I then click update again, thinking not to destroy that nested resource afterall, but it still tries to destroy it.

I looked at the html and found that the ..__destroy hidden input still had a value of true even though I could see the nested resource partial.

So I had to add some javascript to my view like this:

    $('document').ready(function(){
        $("div.nested-fields input[id*='__destroy'][value='true']").attr('value', 'false');
    });

to reset the _destroy field to false.

Do you think this is peculiar to my situation, or would it be worth making a pull request?

**Comment by nathanvda** [comment]
The default rails behaviour will  just send the received form-parameters back to the client, without changing anything. So indeed: deleted items will still be deleted. 

What cocoon does, by default, is "hide" the deleted items.

It is a known bug this does not work correctly, when using turbo-links. So that might explain why deleted items are still visible for you. Although your "fix" code uses document-ready and would not be triggered either --so that got me puzzled: are you using the latest version of cocoon? 

But undeleting? That is indeed a special case, not abnormal. But imho a clean solution would be to reset the `_destroy` flag in the controller. In the controller you know why a validation could fail, and reset some
fields. 

Also, a specific case: `you need at least 3 members` is also easily checked at the client-side, and I would generally hide remove-links when items can no longer be removed. It is easier for me (the coder) and also the user (do not allow actions you know will be wrong). But of course, some validations might not be so easy to check at the client-side.

**Comment by ryan2johnson9** [comment]
Thanks I'll take a look at changing the _destroy flag. That will be a much better solution if it works. I'll try tomorrow and get back to you. So all I need to do is alter the params[my_nested_object..._destroy] = false ?

I don't think I'm using turbolinks.

The form is re-rendered after the validation fails, so that's why the $('document').ready works.

The validation is a very complicated one that must(nearly must) be done client side.

**Comment by ryan2johnson9** [comment]
Thanks for the help, I still went with the original solution as I want to do the validation along with the other ones. However I'm now reconsidering this approach thanks to your comments.

as a side comment: I've been interested in form objects recently, and some are saying that they are a good way to remove 'accepts_nested_attributes_for' in models. However, I have not seen a good implementation for has_many associations, and I would not know where to start replicating the awesome feel that cocoon provides in the GUI with add and remove links. So for the sake of cocoons GUI, I am sticking with nested_attributes_for.

**Comment by nathanvda** [comment]
In the controller, when a validation failed, and you want to set the destroy flag, in the controller, you would need to do something like: 

     @project.tags[1]._destroy = false

Because you will re-render your `@project` (as an example). 

Yes, I still have to investigate form objects myself, curious how they would replace/handle nested items. Personally I find the `accepts_nested_attributes_for` acceptable :) but better options might indeed exist. I have used form objects myself, but only for very simple, specific cases. E.g. a person and her address.

**Comment by adao** [comment]
@nathanvda I get a " undefined method `_destroy=' " exception when attempting your solution.

**Comment by adao** [comment]
I've added attr_accessor to the model. However, when when I set to false in the controller, the nested forms don't show on the view.

**Comment by adao** [comment]
Solved using cocoon's callbacks to hide/show delete buttons to prevent actions that would result in failed validations server side
