### ISSUE TITLE
Revise Readme for link_to_remove_association

### ISSUE THREAD

**Issue by eklamer1** [nathanvda/cocoon#272]
This is a very critical piece of information that cost me a couple of hours before I found it.

"For the JavaScript to behave correctly, the partial should start with a container (e.g. div) of class .nested-fields, or a class of your choice which you can define in the link_to_remove_association method."

It would be nice to stress the importance of this footnote in the section for link_to_remove_association.

Other than that, thanks for the great tool!

**Comment by nathanvda** [comment]
Does this mean you just ignored the example code, or you do not understand haml? I would assume anybody starting with cocoon would first try implementing the samples and go from there. 

Granted it is a lot of documentation to read, everything is covered, but due to the size information is easily skimmed, and also the "important" information. I welcome actual suggestions (or preferably: pull requests) to improve the documentation.

**Comment by eklamer1** [comment]
I read through all of the sections that seemed applicable to my
scenario. Usually, I find that there is enough information in the Readme
that I do not need to go through the examples. I looked at the examples to
figure it out, but I did not look at the fields partial because that part
was simple. I just think that note about the div should be in the
link_to_remove_association section because the remove link will not work
without it. I am just trying to help future users figure this out faster.
