### ISSUE TITLE
Form build will always use SimpleForm if installed

### ISSUE THREAD

**Issue by acurley** [nathanvda/cocoon#291]
In my Rails application, I use both SimpleForm and basic Rails forms within the same app.  As I have the SimpleForm gem installed, all form objects created in my rails app will always return `:simple_fields_for` in `lib/cocoon/view_helpers.rb:46`:

```
method_name = f.respond_to?(:semantic_fields_for) ? :semantic_fields_for : (f.respond_to?(:simple_fields_for) ? :simple_fields_for : :fields_for)
```

In a hybrid environment like my Rails application, shouldn't the query to determine what form type to use be more specific?  Perhaps an implementation is to ask the form object whether it has, as a class ancestor `SimpleForm::FormBuilder` rather than whether it responds to `:simple_form_fields`?

If this sounds amenable, I would be more than happy to submit a PR.

**Comment by nathanvda** [comment]
Indeed, good point. Makes me wonder why you would still use the normal form builder when you have simple_form, since it can do everything the normal builder does but better :smile: **insert tea-drinking Kermit here** :smile: 

Does it give an error, renders the form incorrectly or is this just a purist thing? Which is acceptable, I had just made an assumption which you just proved wrong.

**Comment by acurley** [comment]
I was dealing with a legacy form and didn't want to do the whole refactoring!  I probably should, but the point remains.

For the record, it renders the form incorrectly.  Despite the current form using `form_for`, `SimpleForm` inserts itself into `ActionView::Helpers::FormBuilder` thus successfully responds to `:simple_form_for`.  My guess is that if either Formtastic or SimpleForm is included in the Gemfile, the form would never respond exclusively to `:form_for`.

I will write up a PR tonight.
