### ISSUE TITLE
how to add_associationS ?

### ISSUE THREAD

**Issue by jerome-diver** [nathanvda/cocoon#304]
hello,
I would like to learn if (and how to) be able to add plurial associations.
From an edit view, i have a jquery UI dialog open from a link_to, then this dialog show me some objects list from an other "foreign" model who is linked (nested). Then i can select many of them...
from this point, i would like to just add some associations from selection.
(a pragmatic simple example: i have an article in edit mode view, then this article can have many pictures, so i could choose and select some of pictures i have already, and add them to the article... like a kind of "add_associations"...)
please, could you tell me if this is possible and maybe send me a link who talk about that (or an indication) ?

**Comment by nathanvda** [comment]
For generic question please use stackoverflow.com

**Comment by jerome2** [comment]
@nathanvda 
I would like, but i can not, my reputation (points) not permit me to do that... stackoverflow is very select and i can just read (i can also not gice points... and for me, the opportunity to grow on stackoverflow is ridiculous as inexistant).
I'm sorry...
Also i search on stackoverflow, but not find any answer this point.
I understand you maybe not have time, and i can wait. I hope one day you will have time and want to help me for do that well. Now i'm reading your code and try to understand how this works and try to find a solution. If i find one before you have time or want to help, i will post you this here, maybe you will want to post it on stackoverflaw for some other who can not ask question there (because i know you want to share and help).
Thank you.

**Comment by nathanvda** [comment]
Any stackoverflow member can ask questions: http://stackoverflow.com/help/privileges

@jerome2 == @jerome-diver ???

Your original question is not clear to me and I do not see the direct link to cocoon, necessarily. You seem to be asking a generic question, and stackoverflow is the ideal forum for this. This is a specific forum for reporting bugs and troubles when dealing with the cocoon-gem.

**Comment by jerome2** [comment]
sorry nathanvda, i delete some other un-answered old questions and an old answer who has never been used, and i'm able to post the question on stackoverflow now (my user name is "user2662810").
So i think someone will answer if my question is clearly ask.
Yes, i know stackoverflow is a good site for that, now i understand that i had to remove old un-necessary questions for be able to post question again.
have a good day, and sorry again.
