### ISSUE TITLE
Association contact_infos doesn't exist on ContactInfo

### ISSUE THREAD

**Issue by schoolandrew** [nathanvda/cocoon#308]
I've checked all resources and I still couldn't find anything to help solve this issue. Hope you can lend a hand...

```
= f.simple_fields_for :contact_infos, ContactInfo.new do |f|
	= f.input :contact_type, collection: ContactInfo.types, :selected => true, :remote => true, :input_html=> { :class =>'contact-field', remote: true}
	div.contact
		= render 'super_admin/organisations/contact_fields', f: f
	= link_to_add_association 'add task', f, :contact_infos
```
It doesn't seem to be liking the link_to_add_association line.

I'm getting this sorta exception:
RuntimeError in ShopsController#new
Association contact_infos doesn't exist on ContactInfo

Any leads?

Thanks.

**Comment by nathanvda** [comment]
I am guessing your main form also is using `f` as form-object. If you want a link for each contact-info, you should be using a different variable in the `simple_fields_for` loop. 

Or you will have to outdent the `link_to_add_association` to be outside of the loop.

I see more errors however: 

* you will have to explicitly specify the partial for `link_to_add_association`
* imho it is best to re-use the same partial in the `simple_fields_for` loop, otherwise newly added items will look different (or you will have duplication of code).

**Comment by schoolandrew** [comment]
That fixed it. Thanks,

follow up: 
```
= f.simple_fields_for :contact_infos, ContactInfo.new do |f|
```

Why must I include the second parameter - ContactInfo.new - shouldn't it work without it?

**Comment by nathanvda** [comment]
It depends on what you want. But I am guessing you would want to use it without. If you want to iterate over the available contact-infos you have to get rid of the `ContactInfo.new`. Otherwise it will always show a new _empty_ contact-info.

Mind you: this is standard functionality of the [`fields_for`](http://apidock.com/rails/ActionView/Helpers/FormHelper/fields_for) (which is wrapped by the `simple_fields_for`), I have not suggested to do this in any example I show, so I do not know who suggested you to do it, so you better ask them.

**Comment by schoolandrew** [comment]
thanks nathan, you rock. :+1:
