### ISSUE TITLE
Seems to make problems with carrierwave-base64 gem

### ISSUE THREAD

**Issue by jmuheim** [nathanvda/cocoon#311]
I explain the problem thoroughly here:

https://github.com/lebedev-yury/carrierwave-base64/issues/16

I have no idea on which's side the problem lies, but maybe you could take a look at it, too? Thank you.

**Comment by nathanvda** [comment]
Cocoon does not influence the content of what is posted to the server at all, so I do not see how cocoon could impact this.

**Comment by jmuheim** [comment]
Yes this seems reasonable, but the interesting thing is that the problem only occurs when used with cocoon as nested form fields, otherwise it doesn't occur. So there may be some interaction somewhere. I just couldn't find the problem yet.

Were you able to reproduce the problem with my dummy rails app?

**Comment by nathanvda** [comment]
Are you serious or just saying something to make me look at it? Because from the original issue it is rather unclear what you already tried. And no I did have a look at your dummy rails app, as I still think it could not be a cocoon problem.

Simple test to verify where the problem lies: did you try in the rails console to update the base64 value of an attachment, that would be doing just the same as a controller would do and if that does not work, it is not cocoon.

**Comment by jmuheim** [comment]
I indeed have tried doing these things in the console, but it's a bit hard to work with those very long base64 strings in the console. In fact, it worked for "non-cocoon" attributes, and I will try it again for nested ones, just to make sure it works or it doesn't work.

I will write again here when I can say for sure whether I think cocoon has something to do with it or not (and in fact, I also rather don't think it's cocoon, but who knows?).

**Comment by jmuheim** [comment]
I have added model specs, and in the specs, the update works as expected.

https://github.com/jmuheim/test-carrierwave-base64-update/commit/bd6a40923c159b71a9ef240b760ba3651cf648cf

So it seems it's not a problem on the model's level.

I will try to add feature specs, showing the problem...

**Comment by nathanvda** [comment]
So I am confused: indeed, if I update the base64 string from the rails console, the file is immediately overwritten. If I do the same from the form, I see the correct base64 data is sent to the controller, the permitted parameters are correct, yet I see no change occurring ...

So I dug a little deeper: I added another field to just see if that was saved correctly, and then I noticed the most akward behaviour: 

1) only set the `string_upload` --> nothing is changed
2) set the `string_upload` _and_ another --> both attributes are saved correctly.

So a very wild guess, because the carrierwave internals are a bit too obscure for me, but this leads me to think that _somehow_ the `string_upload=` does not set the `changed` attribute correctly, leading ActiveRecord to think nothing has changed, and nothing needs to be saved? And when one field is correctly seen as changed, ActiveRecord _does_ save and thus saves the changed `string_upload` as well. I have no idea and no clue if this actually true, just a wild guess, but imho this explains the behaviour. 

But aside of that: I am sorry, but still not related to cocoon. I can see in the controller that all data is correctly pushed down, when editing a user, editing existing fields, actually cocoon is not even involved (the nested forms is just standard rails, and everything is set up correctly, hence being able to edit and save an extra field without error).

**Comment by jmuheim** [comment]
You are a hero! Thank you, this helps finding the problem a lot. I already hat something like this in mind, but couldn't phrase it clearly.

I think it really has something to do with the `xxx_changed?` mechanism of ActiveRecord. I will try to manifest the wrong behaviour in some specs and ask the creators of carrierwave and carrierwave_base64 to investigate and fix the problem.

You are released from this task with honor. :+1: Thanks!

**Comment by nathanvda** [comment]
Glad to have been of help :smile:

**Comment by jmuheim** [comment]
One last shot: may it have to do something with `accepts_nested_attributes_for`'s `reject_if: :all_blank` option? That somehow the change of the nested field is not propagated correctly back to the parent object?

I know that on the model level everything seems to work correctly, so this rather is a stupid question again. It's just another shot in the dark... Maybe some strange interaction in the server environment, which doesn't happen when only playing with the models directly?

**Comment by nathanvda** [comment]
Ow maybe that is not so stupid at all, because only when saving in the controller the `accepts_nested_attributes`-methods are invoked.

But unfortunately I verified it (removed the `reject_if`) and it makes no difference. Bummer.

**Comment by lebedev-yury** [comment]
The issue was with the `carrierwave` not marking the attribute as changed. I resolved this issue with the recent version of `carrierwave-base64`

**Comment by nathanvda** [comment]
:+1:
