### ISSUE TITLE
Dynamic values in nested fields partial?

### ISSUE THREAD

**Issue by jmuheim** [nathanvda/cocoon#316]
I have twitter bootstrap tabs in the nested fields partial. They work by specifying IDs to reference individual tabs and panes, and I use `f.object.id` to create them:

```
ul.nav.nav-tabs role="tablist"
  li.active role="presentation"
    a id="text-field-#{f.object.id}-tab" aria-controls="text-field-#{f.object.id}" aria-expanded="false" data-toggle="tab" href="#text-field-#{f.object.id}" role="tab" Zwischenablage
  li role="presentation"
    a id="file-field-#{f.object.id}-tab" aria-controls="file-field-#{f.object.id}" aria-expanded="true" data-toggle="tab" href="#file-field-#{f.object.id}" role="tab" Datei wählen

.tab-content
  .tab-pane.fade.in.active id="text-field-#{f.object.id}" aria-labelledby="text-field-tab" role="tabpanel"
    = f.input :screenshot, as: :text

  .tab-pane.fade id="file-field-#{f.object.id}" aria-labelledby="file-field-tab" role="tabpanel"
    = f.input :screenshot, as: :upload
```

As Cocoon seems to pre-render the partial once and then always inserts the same one when clicking on "add object", it doesn't seem to be possible to generate individual IDs anymore. Is there a workaround? I thought about adding a `cocoon:after-insert` call in JavaScript to manually set them right, but this seems awkward.

**Comment by nathanvda** [comment]
Mmmmmm a new element does not have an id yet. The id is assigned only after insertion in the database. Would you mind explaining what your specific use-case is?

**Comment by jmuheim** [comment]
> Yep, you should be using the callback and instead of the id

Sounds reasonable. But am I the first one in need of this? Maybe somebody has already implemented a similar thing you know of?

> Anyway: you will need to do some manual work anyway, because you can't add the tab and the tab-pane in one go anyway (if that is your usecase).

Can you explain this a bit further?

**Comment by nathanvda** [comment]
Nope I have no idea. I would assume if you tried it it would be obvious :smile: the tab is a linked inside a ul, the tabpane is a separate div, two places to insert stuff, cocoon only inserts a single thing ... Then again: if I understood your usecase correctly.

Maybe you should take this question to stackoverflow.com.

**Comment by AaronCowan** [comment]
you could change this line in `app/assets/javascripts/cocoon.js`
```js
  var create_new_id = function() {
    return (new Date().getTime() + cocoon_element_counter++);
  }
```
to
```js
  var create_new_id = function() {
    return (cocoon_element_counter++);
  }
```

**Comment by nathanvda** [comment]
That is actually pretty dangerous, because that could overrun actual real id's.

**Comment by jmuheim** [comment]
I'm working on a custom solution on my side. Still, I think this would be a useful feature, ain't it possible to implement it on cocoon's side?

**Comment by nathanvda** [comment]
Implementing what on cocoon's side?

**Comment by jmuheim** [comment]
A mechanism which would allow to add a unique ID to each inserted nested fields template. Maybe it would be an option to simply replace `f.object.id` in the template with a unique ID?

**Comment by nathanvda** [comment]
This actually already happens, as I said: I randomise the `f.object.id` to make sure multiple new items can be inserted correctly. But of course, as this `id` is completely random (for good reason) you will not be able to use it, unless you listen to some callback (and then try to find this id). 

The callbacks are the mechanism of choice to change/adapt the generated html before/after insertion into the DOM, so imho there is already a good solution. Otherwise you would have to refer to some javascript callback anyway, in the `add_link_to_association` call?

**Comment by jmuheim** [comment]
But in my case, the `f.object.id` was blank for newly inserted items. Should this be different?

**Comment by nathanvda** [comment]
Apparently this is confusing, so I will try to explain it step by step. I would assume this would also be obvious if you would read the code, but maybe not. 

* when you add a `link_to_add_association` somewhere in the view, a new nested item is rendered and stored in the html of the link
* at that time, the `f.object.id` is `new_<association_name>`
* the `f.object.id` is used in the names/ids to index the correct item in the array of nested items
* when you actually click the link, before inserting the rendered partial, I replace the original `f.object.id` with a random id, when it is used to index (surrounded with square brackets). 
* This is also the time the callback are triggered.

Note: this does not change the value of `f.object.id` at the time of rendering in the rest of the partial, and since it is replaced with a semi-random number this is not useful for your usecase. 

Note: the partial is still only rendered once, and using the callback is imho the preferred to then change e.g. the id for the tab content div. I am definitely not going to add an option to the `link_to_add_association` to call some function after insert (which would have to be a javascript function), because that is exactly why the callbacks are there.

**Comment by jmuheim** [comment]
Thank you for explaining with so much patience. I seem to be a bit stubborn in this respect, as I'm still not 100% sure about it. I'll take a look at the code.

Anyways, the callbacks for sure are the main idea on how to solve my problem, so I close this issue.
