### ISSUE TITLE
cocoon is creating multiple fields and also not rendering the date_select fields 

### ISSUE THREAD

**Issue by kumar91gopi** [nathanvda/cocoon#320]
The issue is the date_select fields are not rendered properly i am not getting the drop-down and also initially when i click add education button 2 or 3 new fileds are rendered (date_select not rendered properly) but when i reload the page and then click add education button then its renders just one field(and that is what i want) but date_select fields are still not rendered properly

from and to are the date_select fields and i got 3 new fields jus by clicking add education once :(
![capture](https://cloud.githubusercontent.com/assets/10248907/10386624/b7aa1c9c-6e94-11e5-86d7-4565d9311099.JPG)
 

here is my nested form
  
![form](https://cloud.githubusercontent.com/assets/10248907/10386729/a804045a-6e95-11e5-80f0-ad98c8e98f46.JPG)

here is my _education_fields partial

![education](https://cloud.githubusercontent.com/assets/10248907/10386698/6ea4ee4a-6e95-11e5-85b6-f19710f60c90.JPG)

 here is my model

```
class Profile < ActiveRecord::Base
  has_many :educations, :dependent => :destroy
  accepts_nested_attributes_for :educations,
                                  :allow_destroy => true,
                                  :reject_if     => proc { |attributes| attributes['institute'].blank? }

  validates :name, presence: true,  length: { maximum: 50 }
  
end
```

**Comment by nathanvda** [comment]
The multiple insertions on one click sounds like a turbolinks problem. That would be related to where you include your `cocoon.js`. The rendering of the `date_select` is not a cocoon problem :)

**Comment by kumar91gopi** [comment]
I have included cocoon.js in assests/javascripts/application.js .
And please can you suggest me what could be the problem with date_select?

**Comment by nathanvda** [comment]
Ok, including in the application.js sounds right. Where do you include the application.js in your layout? It should be in the header (`head`). 

I have no idea what the problem is with the date-select, gathering from your screenshot, I would blame your css, as I do not see any styling for `input` fields. Normally `date_select` renders three drop-downs. You could easily verify if your HTML is correct by inspecting your html (in chrome: right-click on the location and select "Inspect Element"). 

If you need more help concercing the date-select, I suggest you ask it on stackoverflow.com
