### ISSUE TITLE
Populating Cocoon + Autocomplete - error: ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by betinhosaad** [nathanvda/cocoon#327]
I can't figure this out. When I create a new ingredient in the association, it works. However, when I try to find an existing one and reuse its attributes, I get this error: Couldn't find Ingredient with ID=1 for MealIngredient with ID= 

This is my repo https://github.com/betinhosaad/inutree

This is the question on stackoverflow http://stackoverflow.com/questions/34231036/populating-cocoon-autocomplete-error-activerecordrecordnotfound

**Comment by nathanvda** [comment]
Ok, a bit confusing, I had to look at your repo to make sense of it, but as far a I can tell: you want to be able to select an existing ingredient or create a new one. It is in interesting approach you are trying, I need to have a deeper look at it to make sense of it. 

But I have a (different) working approach explained [here](https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-look-up-or-create-belongs_to), and demonstrated in the [demo project](https://github.com/nathanvda/cocoon_simple_form_demo), that might help you already.

**Comment by betinhosaad** [comment]
I'll try to explain better: to avoid duplication, I want to let users to type an ingredient and find it in the dropdown. If the ingredient the user wants isn't there, I want to let them to create a new one, making the app sustainable... I have a new guess which I'll try now just after seeing the links you sent me, let's see what happens. Thank you very much

**Comment by nathanvda** [comment]
(if you edit your original comment, I do not get notified something has changed)

So a bit late, so are you still having problems with this? For me this is unclear, and not sure if
I understand quite what you are saying. I would use `f.association` (which creates for instance a `select`) and then use `select2` to turn the options into an autocomplete. 

But however, if you want to have autocomplete at the `ingredient` level, that will not work, unless you do something in the controller, like you posted (not my favourite option, but it could be working for you). 

If an ingredient is like a tag (e.g. it is just a string you attach and you hope to reuse it), i would instead of using cocoon, look at tagging options. 
If on the other hand, which I would assume, an ingredient has more attributes, that need to be set I would stick to the option I show-case in my demo (meaning: select an existing ingredient, and only create a new one if does not exist yet, with all the needed extra attributes).

**Comment by nathanvda** [comment]
Closed due to inactivity.
