### ISSUE TITLE
Render multiple partials for the nested form

### ISSUE THREAD

**Issue by stinovh** [nathanvda/cocoon#328]
I want to able to render two different partials for a nested form. 
Rendering one partial for a nested form works fine for now but based on an option it should render additional fields.  

I want to give my users the possibility to choose between flexible (populating 3 fields) and fixed (populating 4 fields). We created an extensive Stackoverflow post for this with all the information: 
http://stackoverflow.com/questions/34356003/different-partials-for-same-cocoon-nested-form

Thanks in advance.

**Comment by nathanvda** [comment]
I can think of two different options: 

### Two links 

If I understand correctly, you have two tabs, each tab has its own  `link_to_add_association`. It is possible to overrule the [partial](https://github.com/nathanvda/cocoon#partial) that is rendered, so one link could render the _default_ tab, and for the other you write

    = link_to_add_association 'add something', f, :something, partial: 'fixed_schedule_fields'

### Use a js callback

Instead of using real tabs, you have fake tabs and a single `link_to_add_association` link, and in the callback you check which tab is active, and hide the superfluous field (and maybe set some default values). See [documentation](https://github.com/nathanvda/cocoon#callbacks-upon-insert-and-remove-of-items).

**Comment by nathanvda** [comment]
Closed due to inactivity.
