### ISSUE TITLE
Use associations after calling add_link_to

### ISSUE THREAD

**Issue by G710** [nathanvda/cocoon#330]
Hi,

I have come across a slight problem when using your gem. Maybe you can help me.

Basicallly I want to show my users a form with nested fields for a belongs_to association. Below this form the page should show some information from the models from when the page was loaded.

These associations return nil after calling ```link_to_add_association```

Example:

```
<div class="system_description col-md-3">
    <div id="system_description_list">
        <%= f.association :system_description, input_html: {style: 'display: block'} %>
    </div>
    <%= link_to_add_association 'new', f, system_description, partial: 'description_fields' %>
</div>

<p>German: <%= @measuring_point.system_description.german %></p>
<p>English:  <%= @measuring_point.system_description.english %></p>

```

Calling the bottom lines before the add associations function or leaving it out works just fine. But calling them afterwards doesn't work anymore.

Do you know why?

**Comment by nathanvda** [comment]
Yep, I have a pretty good idea why that is. By default cocoon builds the newly nested object on the association, to make sure any specific parameters you might set on the association are taken into account. However, for a `belongs_to`, when you build an object on the association, since your object can only be linked to one object, you lose the link to the old object. 

The `belongs_to` does not really fit too wel into "dynamic creation" that cocoon offers. There is, however, a simple workaround, if your association is straightforward, you could force cocoon to _not_ create the new object using the association: 

    = link_to_add_association('new', f, :system_description, 
                  partial: 'description_fields',
                  force_non_association_create: true)

**Comment by G710** [comment]
Works like a charm.

Thank you very much!

**Comment by nathanvda** [comment]
:+1:
