### ISSUE TITLE
Partial form added when link_to_add_association is above the fields_for block

### ISSUE THREAD

**Issue by tomvleonard** [nathanvda/cocoon#341]
Given a #new action in ProjectsController...
```
def new
  @project = Project.new
end
```
And projects/new.html.haml...
```
= simple_form_for @project do |f|
  = f.input :name
  = f.input :description
  #tasks  
    %h3 
      Tasks
      = link_to_add_association 'add task', f, :tasks  # <<< NOTE LOCATION ABOVE BLOCK 
    = f.simple_fields_for :tasks do |task|
      = render 'task_fields', f: task
  = f.submit
```

It will render the tasks partial (the behavior you'd expect if you called ```@project.tasks.build``` in the #new action). Only by moving link_to_add_association below the fields_for block will it behave as expected and NOT render the tasks partial. Should the location of the link matter?

Thanks!

**Comment by nathanvda** [comment]
Which version of cocoon are you using? And which version of rails? 

This is a bit weird, because in older versions we did create a new element on the association, and this impacted the collection, but in later versions this was corrected and we first create and then delete the new element from the collection. 

So this should just work, meaning: the location of the `link_to_add_association` should not have any impact.

There is a simple work-around however, to use [`:force_non_association_create`](https://github.com/nathanvda/cocoon#force_non_association_create)
but it should not be needed.

**Comment by tomvleonard** [comment]
Sorry, I should have mentioned that I'm using Cocoon 1.1.2. We're stuck on Rails 3.2 at the moment. When we finally jump to Rails 4.x or 5.x this should be a non-issue then. I'll take a look at :force_non_association_create. Thank you!

**Comment by nathanvda** [comment]
I use cocoon in both rails 3 and 4 projects, so you should be able to just upgrade.

**Comment by tomvleonard** [comment]
But of course. I was looking at the development dependencies listed on rubygems.org and thinking runtime dependencies. Time to upgrade. Thanks once again!
