### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by TeTiRoss** [nathanvda/cocoon#344]
How to test adding image that is adding by `cocoon` methods  with Capybara `attach_file` method?

``  
      attach_file( "file_field", "#{Rails.root}/spec/assets/example.jpg" )
`` 
According to Capybara docs: "The file field can be found via its name, id or label text."

**Comment by nathanvda** [comment]
Your question is unclear. You are not able to execute the `attach_file` because `file_field` does not exist? Replace `file_field` in the shown code with the name, id or label text of the file field (as the docs state). Is that really your question? 

Most likely you are better of asking this type of question on stackoverflow.

**Comment by TeTiRoss** [comment]
Ok, I`ll try to ask it on stackoverflow.
