### ISSUE TITLE
combine with helpers ?

### ISSUE THREAD

**Issue by Sashkan** [nathanvda/cocoon#348]
Hi,

I'm trying to combine cocoon and the cloudinary file upload helper, but this doesn't seem to work, I think I didn't understand how to manage nested inputs. I'm trying to upload my files using the following, but this doesn't display any input

```
<div class="col-xs-2">
          <%= link_to_add_association f, :media, class: "add-file hidden", wrap_object: Proc.new { |medium| medium = Image.new } do %>
          <%= cl_image_upload_tag(:image_id, html:{class:'btn btn-success'}) %>
          <% end %>
</div>
```

While the following displays two inputs :+1: 
```
<div class="col-xs-2">
          <%= link_to_add_association f, :media, class: "add-file hidden", wrap_object: Proc.new { |medium| medium = Image.new } do %>
            <i class="fa fa-picture-o"></i><p class="hidden-xs">&nbsp;&nbsp;Image</p>
          <% end %>
          <%= cl_image_upload_tag(:image_id, html:{class:'btn btn-success'}) %>
        </div>
```

How can I turn the cloudinary file input into the nested element ?

**Comment by nathanvda** [comment]
Is this the first time you are working with cocoon? Did you read the documentation? Do you understand where what you are trying to do is deviating from what is generally proposed in the documentation? Could you explain that to me? Could you explain what cloudinary is? How do your models and associations look? 

Maybe your problem is very clear to you, but it definitely is not to me. I know cocoon, but your code is not recognisable to me at all (your formatting does not help either).

Weird things: 

* I see no reference to a form: how do you iterate over the nested elements
* how does your nested-fields partial look
* why put the helper inside the link (which I assume will add the upload field) ? Imho this does not even generate valid html
* why does the `wrap_object` create a new object without any link to a parent? Makes me wonder there even is a nested model? 

Please look at the documentation, at the examples how I intended this gem to be used. Or at least explain in a little more detail what you are trying to do. Give me a little context.

**Comment by Sashkan** [comment]
My bad, indeed, it was a simple mistake of mine: instead of building my nested form using a builder component, I tried to do so using the template, which obviously didn't work ! Thanks for answering so quickly, and once again, sorry for the silly question.
