### ISSUE TITLE
Incluing the gem does nothing

### ISSUE THREAD

**Issue by ror6ax** [nathanvda/cocoon#350]
Hi, I'd love to use the gem, but for some reason gemfile + \\ require cocoon does not add JS into the project. add/remove links do nothing with no errors, can't find expected code in compiled application.js... Any hint how might I debug what's wrong?

Thanks,
Greg

**Comment by nathanvda** [comment]
Do you compile `application.js` in development? That is really cumbersome, because you will have to do `rake assets:precompile` after bundling (manually). Normally in development Rails doesn't compile the assets, in which case it just includes all the files (from the manifest)(which is easier during development).

Also if you have done `rake assets:compile` once, it will always take precedence, even in development. So you might just want to delete your assets (if you compiled them just for testing).

**Comment by ror6ax** [comment]
Fixed the issue. Got one question though. How do I make `link_to_add_association` an image?

`= link_to_add_association =image_tag 'img.png' ', f, :stuffs` does not work...

**Comment by nathanvda** [comment]
The `link_to_add_association` works in the same way as the normal `link_to` so it accepts a block to be rendered. So in your case that would be

```
= link_to_add_association f, :stuffs do 
  = image_tag 'img.png'
```

But you could also write 

    = link_to_add_association image_tag('img.png'), f, :stuffs

Anyway, that is pretty basic rails/haml, but glad you got your issue fixed. For future people encountering the same problem it might be helpful to explain how you fixed it?

**Comment by ror6ax** [comment]
It was really precompiled js from the previous run. Noob's thing, really :)
Last thing - is there a way to create a cocoon nested form without the first element?
Now I have my first auto-generated for me on the page already. I'd love user to add it via link_to_add if they wanted...

Thanks, and sorry for the off topic questions!

**Comment by nathanvda** [comment]
That is perfectly possible, all my examples are built up like that? Maybe you should show some code, but it sounds like you placed the `link_to_add_association` inside the `fields_for` loop? (so it would only appear if there is an item --but it would also appear for each item).

**Comment by nathanvda** [comment]
Closed due to inactivity.
