### ISSUE TITLE
Get nested form field id number from cocoon

### ISSUE THREAD

**Issue by wolfieorama** [nathanvda/cocoon#362]
Hi, Apologies if this question is repetitive: Is there a way to get the unique IDs generated whenever a new field is added to a form, the IDs are different every time, and I believe it is generated by Cocoon since these fields are added dynamically by cocoon, how can I pass the IDs dynamically for use in a jQuery selection

**Comment by nathanvda** [comment]
Can you explain what you are trying to do in more detail, because in general there is no need to be referring to the id's. Instead you use the callbacks to manipulate the newly added html before or after insertion in the page. See the [documentation](https://github.com/nathanvda/cocoon#callbacks-upon-insert-and-remove-of-items) for some examples.

**Comment by wolfieorama** [comment]
@nathanvda I am not sure if the callbacks will apply in my case but this is my use case.

I want to generate some dynamic select box menus, e.g where if field 1 in the nested form is selected then all sub field1 related records are displayed in the second select box, for field2 as well and so forth.

since i need to refer to specific field within the insert grouped of fields (in the form) , the `cocoon:after-insert` refers to the form but not specific field within the form...... or i am missing anything in the callback

**Comment by nathanvda** [comment]
The callback gets as parameter the newly inserted item, not the complete form.

For example, an question I answered on stackoverflow: http://stackoverflow.com/questions/35569381/cocoon-how-to-get-inserted-item-id

**Comment by wolfieorama** [comment]
@nathanvda i totally get that now, but still the inserted item in my case is a from with many fields not a single item

**Comment by gregblass** [comment]
Hey there @nathanvda !

In my case, I need the ID in order to replace an image in the nested fields in an AJAX call. In other words, I have multiple nested fields that have images that can be uploaded/associated with them. So when the request comes back from the server, it needs to know which one to replace the image placeholder with. So I need to get that new_id field. I can use a callback to just put an ID tag on the div, but how would I get the ID from that `added_thing` in the callback?

I get why you are steering people away from using it in normal circumstances. And if the answer is, "its not possible/available/accessible", I understand.

Thanks!

**Comment by gregblass** [comment]
Nevermind, your comment here helped me: https://github.com/nathanvda/cocoon/issues/394#issuecomment-255326006 - All good, thank you @nathanvda
