### ISSUE TITLE
'Before remove'  fade effect doesn't work on dynamically added items, works on existing items.

### ISSUE THREAD

**Issue by mahendhar9** [nathanvda/cocoon#370]
Hello.
Can someone help me in figuring out the issue.

```
// _form.html.erb

<%= simple_form_for @institute_profile, url: url, method: method do |f| %>
<div id="courses">
    <%= f.simple_fields_for :courses do |s| %>
  <%= render 'course_fields', f: s %>
  <% end %>
  <%= link_to_add_association  f, :courses do %>
  <span class="creat-file">Add Course</span>
  <%= fa_icon "plus-circle" %>
  <% end %>
</div>
<% end%>
```

```
// _course_fields.html.erb

<div class="nested-fields">
  <%= f.input :name, label: "Course Name" %>
  <%= f.input :description, label: "Course Description", input_html: {:rows => 3} %>
  <%= link_to_remove_association "Remove Course", f %>
</div>
```

```
// Before adding new item, animate. This is working.

$('#courses').on('cocoon:before-insert', function(e, course) {
    course.fadeIn('slow');
  });
```

```
// Before removing an item, animate. This is working on existing items on edit page, 
but when I add new item and remove it, the fade effect isn't working

$('#courses').on('cocoon:before-remove', function(e, course) {
    $(this).data('remove-timeout', 1000);
    course.fadeOut('slow');
  });
```

**Comment by nathanvda** [comment]
Mmmm did you check the obvious: maybe newly created items are not inside the `#courses` div?

**Comment by mahendhar9** [comment]
@nathanvda, when on the edit page, the existing items are directly under the '#courses' div. When a new item is added, the hierarchy is #courses > .links > newly-added-item. Is this normal?

**Comment by nathanvda** [comment]
A bit unclear, because I do not see a `.links` class in the code you showed? 

Check out 

* the wiki page with ERB examples: https://github.com/nathanvda/cocoon/wiki/ERB-examples
* the sample project: https://github.com/nathanvda/cocoon_simple_form_demo (which includes the remove animation as well)

**Comment by mahendhar9** [comment]
Sorry @nathanvda, I did not copy it the _form.html.erb correctly. Found out the issue. The link_to_add_association was wrapped in another div. Removed that div and now it's working fine.

The previous hierarchy was #courses > .links > .another-div > newly-added-item
Now, the hierarchy is #courses > .links > newly-added-item

**Comment by nathanvda** [comment]
Ok, great you solved it. Still a bit weird, because events just bubble up, and as long as you define the event-handler on a outer-most level (e.g. `#courses`) it should always be handled correctly (no matter how deep). So only if the new item is _not_ contained in `#courses` or maybe you have another event-handler which blocks further propagation could explain this behaviour imho. Anyway :+1: :smile:

**Comment by mahendhar9** [comment]
Not sure @nathanvda :) Thanks for the support.
