### ISSUE TITLE
Cocoon with single form?

### ISSUE THREAD

**Issue by pablougas** [nathanvda/cocoon#371]
Is there a way to use cocoon to use a single form and items to a list of items? 

For example, if I had an "ORDER" and on my Order edit page I could have a single drop down form that displays ITEMS and then adds selected items as editable objects (e.g.: adjust quantity, pricing, discounts, etc)  to an ORDER_ITEMS page that is rendered all in the same view?

**Comment by nathanvda** [comment]
It is a bit unclear what you are asking, because cocoon always uses a single form. So I am guessing you mean something else? 

Things I do not understand in your description: 

* "items to a list of items" ?? 
* "a single drop down form" ??
* an ORDER_ITEMS "page" but rendered in the same view? 

But, if I understand correctly, instead of having a single button to add a new element, you first want to select an item from a drop down, and then edit that item? 

Not entirely sure if cocoon is the best solution, but I can think of a few solutions. 

### 1. Use a dropdown and a single `link_to_add_association` button 

* add a dropdown with all items that can be added
* add a `link_to_add_association` button
* add a `before-insert` callback, that will look-up and set the correct values upon inserting, depending on the selected item (use ajax) 

### 2. Add a `link_to_add_association` per item

I have no idea how many "item-types" you have (your example is probably intentionally left unclear, but that never helps in thinking about a solution)

* add a `link_to_add_association` per type, and use the [wrap_object](https://github.com/nathanvda/cocoon#wrap_object) option to build the form. No ajax needed now. 

### 3. Refinement of 2.

* hide all those added buttons
* add a drop down and upon change it triggers the corresponding button

**Comment by pablougas** [comment]
Sorry, my thoughts were a little jumbled yesterday. I tried to find documentation on the link_to_add_association button as you mentioned but only found items pertaining to cocoon. 

Essentially, what I am trying to build is a form that allows for the selection of a category, that category is then used to display a second select object with a list of products that fall under that pre-selected category. Then an "add item" button that adds that product to a list of items below it. 

From Railscast episode #196 and your advice I am pretty close. I've used attr_accessor to allow my quote form to display the category and products dropdowns on my form now and I have a link_to_add_fields that adds the editable form objects. However, I need to figure out a way to grab the selected options in the form and carry those values and then reset the options... Am I going about this the right way? I know cocoon uses a single form but it generates that form with every click, I simply need the single form rendered only once... I hope this makes better sense and that I could buy you a beer as I've used cocoon many times other ways and it's become one of my favorite gems.

**Comment by pablougas** [comment]
Nathan, sorry for the trouble, I just realized that I shouldn't reference the product in case it's ever removed or destroyed and should just copy the name into an item_name column. I appreciate all the help and apologize for the run around.

**Comment by nathanvda** [comment]
Yep, the `link_to_add_association` is the command, from cocoon, that renders a link/button to add a new nested item. 

Actually your explanation is still very confusing to me. Cocoon does not generate the form, it just inserts the partial with the nested children, which is rendered only once, server-side and copied when the link is clicked. 

Maybe you should show me some code. Or maybe you should ask this on stackoverflow, where more people can help you.

**Comment by nathanvda** [comment]
Closed due to inactivity.
