### ISSUE TITLE
My Nested Form send values null

### ISSUE THREAD

**Issue by mariomachuca** [nathanvda/cocoon#375]
My nested form don't save nested values, values are null in database and not save

**Comment by nathanvda** [comment]
I would need to see some code to be able to say anything sensible. Show me the controller, model and view-code (or a simpler version that reproduces the problem, if your code is too complicated).

Please take the time to explain the problem clearly, and explain/show me what you tried already, so I can help you better.

Otherwise this is going to be hard. Wait for me to find my magic thinking hat, crystal ball, magic wand, and awaken my psychic powers 😈 😉

**Comment by nathanvda** [comment]
Closed due to inactivity.
