### ISSUE TITLE
Possible to grab dynamic ID for use in other divs associated with the form?

### ISSUE THREAD

**Issue by padrigirdap** [nathanvda/cocoon#394]
Just as a precursor, my form is set up for Visualizations has_many Rows, Rows has_many Panes.
I created a dropdown button that conceals the three choices for users on selecting how many instances of a Pane item they want generated (1, 2, or 3). It works great the first time around. But the button relies on the data-toggle attribute as well as the subsequent div id being the same (in the example below: data-toggle and id are both "example-dropdown-1". This causes a problem when I need to add another row. The button is placed again but because of the identical id, the hover function shows up only for the top button. 

```
  <div class="field">
    <%= f.label :rowtitle, 'Row Title', class: "row_title" %>
    <%= f.text_field :rowtitle, class: "row_title_input" %>
    <div class="pane_dropdown">
      <button class="fa fa-plus-square fa-2x" type="button" data-toggle="example-dropdown-1"></button>
      <div class="dropdown-pane" id="example-dropdown-1" data-dropdown data-hover="true" data-hover-pane="true">
        <%= link_to_add_association 'Add 1', f, :panes, count: 1, partial: 'one_pane_field', id: "testingpaneone" %>
        <%= link_to_add_association 'Add 2', f, :panes, count: 2, partial: 'two_pane_fields', id: "testingpanetwo" %>
        <%= link_to_add_association 'Add 3', f, :panes, count: 3, id: "testingpanethree" %>
      </div>
    </div>
  </div>
```

I was hoping to somehow grab the div ID and assign it each time an instance of a Row is generated. I imagine it needs to happen using `after-insert`..But frankly I'm not positive on the javascript necessary to do this. But I'm close!

```
  $('#rows')
  .on('cocoon:after-insert', function() {
    $('.fa-plus-square').attr('data-toggle', 'dropdown2');
    $('.dropdown-pane').attr('id', 'dropdown2');
    $('.pane_dropdown').foundation();
```

Give's me the the appropriate attributes..But i'm just not sure how to assign a unique one each time a user generates an instance of the partial. I was hoping to use the dynamic ID the partial gives out because it would also solve another problem I have which is assigning ids dynamically for styling.

**Comment by nathanvda** [comment]
Cocoon does not generate div id, it just renders your nested-partial, and repeating div's should not have an ID or your HTML is invalid (an ID is intended to be a unique identifier, so it only should be on the page once). When using the callback, normally there is no need to refer to ID's, and definitely not for styling. 

However, it seems that foundation can only link to items based on ID to get your dropdown working (your title has me confused). The only thing you need to do in the callback, is generate a unique ID for that partial. That could be based on visible rows, that could be completely random, based on time. 

Furthermore your callback is wrong, because it is not using the inserted html, you are just selecting _all_ `.dropdown-pane` again. 

Do something like 

```
$('#rows').on('cocoon:after-insert', function(e) {
   var dropdown_id = 'dynamic_dropdown-' + $('.pane_dropdown').size();
   
    $(this).find('.fa-plus-square').attr('data-toggle', dropdown_id);
    $(this).find('.dropdown-pane').attr('id', dropdown_id);
    $(this).find('.pane_dropdown').foundation();
})
```

The id calculation is just an example. Since you have an initial id `dropdown2`, I renamed the id as to have (hopefully) no clashes. You wil probably have to fix this for your page.

But this should get you started. 

Please note that this is all just merely standard html/css/jquery, and the github issues are actually intended when people find bugs when using cocoon, questions like these you should ask on stackoverflow. I get notified when questions on stackoverflow are tagged with `cocoon-gem`.
