### ISSUE TITLE
Cannot save model when association has belongs_to defined

### ISSUE THREAD

**Issue by smoothdvd** [nathanvda/cocoon#400]
I have to two model:
```
class Stage < ApplicationRecord
  has_many :distributions
  accepts_nested_attributes_for :distributions,
                                reject_if: :all_blank,
                                allow_destroy: true
end

class Distribution < ApplicationRecord
  # belongs_to :stage

  validates :period, :proportion, presence: true
  validates_uniqueness_of :period, scope: :stage_id
end
```

If I uncomment "belongs_to :stage", in create method form, it always says: "......stage required".
If I comment it, the  validation of uniqueness is not working, but stage and distributions will save successfully.
How to resolve this?

**Comment by nathanvda** [comment]
It is not the `belongs_to :stage` but probably the `validates_uniqueness_of` that is blocking the save imho. Or maybe you should add: `belongs_to :stage, inverse_of: :distributions`.

While the `validates_uniqueness_of` should work, not really sure if this can work, because I am not sure how and when rails assigns the `stage_id` when saving it all together in one go. Maybe making explicit that `stage` is the inverse-of might help rails to make better decisions (but a wild guess for now).

**Comment by smoothdvd** [comment]
@nathanvda I now add optional: true in Rails 5

**Comment by nathanvda** [comment]
:confused: hmmm? You add `optional: true` where? and to what effect? is it solved now? 

I read in rails 5 you have to add the `inverse_of:` option to make the `belongs_to` work/behave correctly.

**Comment by smoothdvd** [comment]
@nathanvda I get the info from this blog: [Rails 5 makes belongs_to association required by default](http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html)

**Comment by nathanvda** [comment]
Ok, thanks. So I think your issue is solved now?

**Comment by smoothdvd** [comment]
@nathanvda Yes.
