### ISSUE TITLE
Applying Cocoon Nested-Fields Index to Other Attributes

### ISSUE THREAD

**Issue by nickooolas** [nathanvda/cocoon#403]
First just wanted to say, great work with Cocoon @nathanvda, has saved me lots of time already 👍 

Now, you know how Cocoon generates unique HTML `name` for any newly added `nested-fields` (looks to be epoch timestamp)?

`<input name="insurance_application[addresses_attributes][1483682058600][street]"....>`

I'm talking about *this* one `[1483682058600]`

**Is there any way I can get Cocoon to apply that same unique ID (or any other unique ID for that matter if need be) elsewhere in the `nested-fields` partial prior to insertion?**

In my case, I've implemented the newly added group of nested-fields as *Bootstrap Accordions*, and as you're probably aware, they require unique ID's.

**CURRENT STATE:**
A snippet below of the partial (not all of it) - you can see I use `<%= local_assigns[:unique_id] %>`, to ensure any that are rendered by rails are unique for each address.  Now I know I can pass a local to it through `link_to_add_association`, but this value is fixed across all newly generated `nested_fields` when it comes to Cocoon inserting new ones on top of any rails rendered.

*__address_fields_.html.erb*

```HTML+ERB
<div class="address-fields nested-fields">
  ...
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading<%= local_assigns[:unique_id] %>">
                <div class="row">
                    <div class="col-md-9">
                        <h3 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= local_assigns[:unique_id] %>" aria-expanded="true" aria-controls="collapse<%= local_assigns[:unique_id] %>">
                                <%= address.titleize %>
                            </a>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="panel-collapse collapse" id="collapse<%= local_assigns[:unique_id] %>" role="tabpanel" aria-labelledby="heading<%= local_assigns[:unique_id] %>">
                <div class="panel-body">
                    <div class="row">``
                        <div class="field col-md-7">
                            <%= f.input :street, as: :string %>
                        </div>
                        <div class="field col-md-5">
                            <%= f.input :suburb, as: :string %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  ...
</div>
```

**DESIRED STATE:**
Could I use Cocoon, perhaps before-insert callback, to apply the unique ID in those places where I currently have used `<%= local_assigns[:unique_id] %>`?

An example from above would mean that Cocoon modifies like such before-insertion:

`<div class="panel-heading" role="tab" id="heading<%= local_assigns[:unique_id] %>">`

**becomes**

`<div class="panel-heading" role="tab" id="heading1483682058600">`

**Comment by nathanvda** [comment]
The only way is to use the cocoon callbacks to manipulate the html to be inserted before or after insert. The ID that cocoon generates is completely random, just to make sure that upon save rails will recognise it as a "new" child. I think it would be easier for you to use some kind of logical number, like the order-number of the panel (or last panel-nr + 1 when you start deleting). 

The partial is only rendered once, at server-side. 

Cocoon inserts a random/unique ID in js (so it cannot be used in the partial anywhere). 

An extremely dirty trick, which I would advice against: if you use the same format as rails do when rendering ids (rails will write something like `new_person` or `new_people` for new items --when inserting multiple children we need something more unique, so we use a random ID). 

So if you check the code the code tries to replace `_new_<association-name>_` so if you name your id-fields something like `collapse_new_address_field_` theoretically that could work. 

The problem is: the code will try singular first and then plural and check if something was changed. So if you fill in the singular but the form/rails is using plural, you will actually break the form. So I would strongly advice against that, and instead use the callbacks to replace something you know. 

E.g  you `local_assigns[:unique_id]` is something fixed you can just replace upon insertion.

**Comment by nickooolas** [comment]
Thanks for the in-depth response and watch-outs @nathanvda. 

On that advice, I've implemented the logic to replace the `local_assigns[:unique_id]` as callbacks and is working nicely now 👍 

Thanks again!

**Comment by sanyam-j** [comment]
@nickooolas How did you do that. Can you give some code reference. It will be useful. Thanks in advance

**Comment by Mirv** [comment]
@sanyam-j .... see the link above your post?  Follow that one ... to issue #419
