### ISSUE TITLE
Rails 5 + Turbolinks - Clicking add new *thing* duplicates.

### ISSUE THREAD

**Issue by sbramlett** [nathanvda/cocoon#409]
I'm using this with Rails 5 on my recipe box app. It creates multiple ingredients when clicking the button once. It will randomly create 3, 6, 9 of them - instead of just one. I could be calling it wrong?
`= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"`

I have my `application.js` call in the header and `//= require turbolinks` is near the bottom.

You can see it here... 

https://github.com/sbramlett/recipe_box/blob/master/app/assets/javascripts/application.js

https://github.com/sbramlett/recipe_box/blob/master/app/views/layouts/application.html.haml

**Comment by nathanvda** [comment]
Mmmm that seems ok. 

Is that the repo of your application: https://github.com/sbramlett/recipe_box ?

I will have a look later today.

**Comment by sbramlett** [comment]
That's it! I appreciate you taking the time to look at it for me. 👍

**Comment by Mirv** [comment]
@sbramlett Hi, I was following along & I had a similar issue with the callbacks not setup correctly.  I know in the formtastic demo Nathan doesn't populate the callbacks, but in the [simpleform ](https://github.com/nathanvda/cocoon_simple_form_demo/blob/master/app/assets/javascripts/projects.js)demo he does.  

Here is a copy of the fix where Nathan corrected my callbacks  ... [Github Link](https://github.com/Mirv/b4_test/pull/1).

I notice you don't have any callbacks via javascript listed & not sure if that will actually help or not but thought I'd mention it was one of the final fixes before my test project got rid of the clicking to add a field would give me randomly give me extra fields.

**Comment by sbramlett** [comment]
I added the `application.js` to head like he mentioned and made sure the `turbolinks` was at the bottom of the `application.js` file. I'm not sure where the duplication is happening. That's what confused me.

**Comment by Mirv** [comment]
I was in about the same place recently!  I knew nothing of jquery. The fix was to add a file of jquery in:

`app/assets/javascript/<name of controller>.js`

In my case it was the `app/assets/javascripts/continents.js` (https://github.com/Mirv/b4_test/blob/master/app/assets/javascripts/continents.js).

I had been doing customized `before-insert` behavior in the continents.js file.  From what Nathan mentioned, if you use a before-insert, you need to terminate it with 'after-insert'.  So the browser would update correctly the first time & the following times it would add too many fields for me (until I either closed the browser or reset the server app).

If you don't want to read the change log from github that I linked - here's an example of one of the corrections to solving my problem ...

```
  $(document).on('cocoon:before-insert', 'form', function(e,region_to_be_added) {
     console.log(region_to_be_added);
     console.log("Regions before-insert");
     e.stopPropagation();
     region_to_be_added.fadeIn('slow');
   });
   $(document).on('cocoon:after-insert', 'form', function(e,region_to_be_added) {
     console.log(region_to_be_added);
     console.log("Regions after-insert");
      e.stopPropagation();
      region_to_be_added.fadeIn('slow');
    });
```

**Comment by Mirv** [comment]
I installed your repo & ran it - the behavior is different - yours happens right away.  I'll poke it more after lunch.  My first instinct is that you have an extra '=' symbol in there somewhere for the rendering - it happened to me once...I think but that was last year.

**Comment by sbramlett** [comment]
I noticed the load on it is weird for my CSS as well. Maybe I'm missing something a small `=` or `-` like you mentioned. Thanks for the assistance. 😃

**Comment by Mirv** [comment]
I've seen it happen on bad indentation too...let me implement the after calls & see if that solves it in your repo.

**Comment by Mirv** [comment]
Ok, I loaded that before & after callbacks I posted above - they fire twice each for one click of the button.

**Comment by Mirv** [comment]
Update:  Cutting out turbolinks seems to make it run fine ...

First I added that code snippet for the callbacks that hook into cocoon ...

```
$(document).on("ready", function() {
    console.log("-- Page Load --");
  $(document).on('cocoon:before-insert', 'form', function(e,field_to_be_added) {
    console.log(field_to_be_added);
    console.log("field add - before-insert");
    e.stopPropagation();
    field_to_be_added.fadeIn('slow');
  });
  $(document).on('cocoon:after-insert', 'form', function(e,field_to_be_added) {
    console.log(field_to_be_added);
    console.log("field add - after-insert");
    e.stopPropagation();
    field_to_be_added.fadeIn('slow');
  });
  $('.ingredient').on('cocoon:before-remove', function(e, region_to_remove) { 
    console.log("Remove Region");
    $(this).data('remove-timeout', 1000); 
    region_to_remove.fadeOut('slow'); 
    e.stopPropagation();
    });  
  $('.ingredient').on('cocoon:before-remove', function(e, country_to_remove) { 
    console.log("Remove Country");
    $(this).data('remove-timeout', 1000); 
    country_to_remove.fadeOut('slow'); 
    e.stopPropagation();
  }); 
});
```

Then I went and eliminated turbolinks & added the callback file (recipes.js) to the list to load - since apparently it doesn't load automatically (note, I deleted the recipe.coffee since I don't use it too) ...

**App/assets/application.js**
`//= require jquery
//= require cocoon
//= require jquery_ujs
//= require bootstrap-sprockets
//= require recipes.js
//= require_tree .`

Now, having said that ... I know there's a better fix, just trying to remember it.

**Comment by sbramlett** [comment]
I would like to keep turbo-links and run it as intended. I know @nathanvda mentioned this could be done. Maybe he sees something we are missing?

**Comment by Mirv** [comment]
My bet on your problem ... you are loading turbolinks twice.  I'm honestly not sure if that's the entire fix - you might have to have the above code I included too.

You have it once in the `app/assets/javascript/application.js` ...

```
//= require jquery
//= require cocoon
//= require jquery_ujs
//= require bootstrap-sprockets
//= require turbolinks
//= require_tree .
```

Here again ... in the `app/view/layouts/application.html.haml` ...

```
!!! 5
%html
%head
	%title Recipe App
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
```

**Comment by nathanvda** [comment]
The fix was really easy actually (but also to overlook): when inspecting the html I saw the following: the `<head>` section was empty, and all js was included in the body. That made me look at your `application.html.haml` and then I saw your `%html` and `%head` tag are at the same indentation level. 

The fix is easy: 

```
!!! 5
%html
  %head
    %title Recipe App
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = csrf_meta_tags
  %body
    -# ... [snipped for brevity]
```

(I created a pull request with the fixed application layout)

Thank you @Mirv for your attempt to help, however 

* the error in your repo was indeed similar, however: you loaded the application.js _explicitly_ in the `body`, while here it happened by accident (typo). That was the only error here.
* there is no need for callbacks if you do not need them (while it might be useful for debugging purposes, but not really sure what we learned here)
* somehow in the last comment you are really confused: in the `application.js` you specify which javascript files should be loaded, but you always have to load the `application.js` file in your application layout (so they were not loaded twice at all)

**Comment by Mirv** [comment]
> Thank you @Mirv for your attempt to help, however

Apologies for muddling the fix!  

I'm just trying to learn by trouble shooting too - good catch on the spacing fix for HAML dropping the code out of the head!

It was weird, it looked like he had been tabbing or double spacing for his haml.  I either fixed that spacing without thinking about it -in the cloud9 ide where I loaded the repo or my cloud9 showed it all equally spaced out - though i can clearly see when I pasted it back in there - it's a 4 space set instead of the double spaces he had.

**Comment by nathanvda** [comment]
No apologies needed, I think it is awesome you were trying to help! :+1:

**Comment by sbramlett** [comment]
Yeah @Mirv - I appreciate the assistance. Best way to learn is to jump in with the sharks. 😄

**Comment by acrolink** [comment]
@Mirv 

Thank you, that solved the issue.

**Comment by loso-nd** [comment]
Hi, I am having a similar issue with my code. I tried following along above, but have not been able to resolve this issue. Any suggestions?

**Current Error**
`Sass::SyntaxError - Invalid CSS after "...ass}: #{$value}": expected "{", was ";":`

Indicated error exist here line 6: `app/views/layouts/application.html.haml`
Line 6:  `= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true`

**application.html.haml**

`!!! 
%html
  %head
    %title EffortForecast
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/login_modal'
    %section
      = render 'layouts/header'
    = content_for :subnav

    %section.container-fluid
      .flash-messages= render 'layouts/flash_messages'
      = yield`


I have also posted this question on stack Overflow [here 
      
](https://stackoverflow.com/questions/72396489/rails-s-error-invalid-css-after-ass-value-expected-was)
