### ISSUE TITLE
What is the reason for having the full coded template in the `data-association-insertion-template` attribute?

### ISSUE THREAD

**Issue by eric-norcross** [nathanvda/cocoon#410]
Forgive me if this isn't the best place to ask this question; while browsing though my console I noticed that the fully rendered partial is embedded into the `data-association-insertion-template` attribute. 

I'm guessing this is to avoid the extra setup of a corresponding route and controller action to handle it though an ajax request when the user clicks the add button?

**Comment by nathanvda** [comment]
Rails has the ability to save nested forms, using the `fields_for` form-helper and `accepts_nested_attributes_for`, but this is not dynamic. What cocoon does is pre-render one partial server-side, stores it in the attribute, and will insert it when clicked. 

So indeed: there is no communication with the server until you `POST` the form. 

This is the easiest way to accomplish that indeed.

Note that because everything is saved in one go, for most of my recent applications, this does not always works UI-wise. Most of the times I want to add and delete nested items, on the fly, and will in those cases use straightforward ajax to insert/save/delete nested items. Every action is directly saved to the db. It depends on the use-case what fits best for your application.

**Comment by nathanvda** [comment]
(not sure if that was clear or not?)

**Comment by eric-norcross** [comment]
Got it. So, the reason I ask is because there are instances when pre-rendering isn't suitable, both for the reason you mentioned but also when elements of the nested form are dependent on attributes set on the parent. 

If I were to fork the project and integrate the dynamic components, would you be opposed to merging that functionality in?

**Comment by nathanvda** [comment]
If you mean using javascript, you can already use callbacks to change the inserted partial before insertion (based e.g. on a choice made in the parent). Please remember: the intention of cocoon is manipulating a form with nested _before_ sending any data to the server. 

If you mean using ajax/xhr. then I think you are talking about a different solution. At this moment I am not invested in _extending_ cocoon greatly, I prefer to keep cocoon simple and to the point. Also with the present wealth of js frameworks, this also changes front-ent choices at this time for me.

But maybe if you can elaborate on the the solution/direction you are thinking about? 

I have been thinking myself to make cocoon a little more modular so e.g. the "insert a partial here" can be reused (I use my own copy now in my own code in some projects).

**Comment by eric-norcross** [comment]
My initial thoughts were along the lines of adding an additional helper method, something like `link_to_async_add_association` which would utilize the existing cocoon architecture but handle generation on the fly. 

Using the `before-insert` hook is defiantly workable; but depending on the scale of the project, that could require writing a lot of JS code to handle various configurations; some of which may be similar to existing backend functionality. 

Another possible benefit of adding an async method would be easier handling of `has_one` and limited associations.

I'd be interested in discussing it further if you are; that being said, I totally respect your stance if this isn't the direction you want to take the project.
