### ISSUE TITLE
Nested attributes aren't saved...

### ISSUE THREAD

**Issue by knopfler81** [nathanvda/cocoon#415]
Hi there,

I am having a similar issue as **356**... ( I am on Rails5).
I am stuck for a while...

My form isn't submitted...

Hope you could help :) 
_form.html.erb
```
<div class="container">
  <div class="row">
    <%= simple_form_for @event do |f| %>
    <div class="col-xs-12">
      <h3>Your event to share</h3>
      <%= f.input :name, label: "Event's name" %>
      <%= f.input :total_price, label: "What is the total price" %>
      <h3> Add your friends to share the bill</h3>
      <div id="participants">
        <%= f.simple_fields_for :participants do |participant| %>
          <%= render "participants_fields", f: participant %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "add a friend", f, :participants, partial: "participants_fields", class:"btn btn-primary" %>
        </div>
      </div>
        <%= f.button :submit %>
    </div>
  <% end %>
  </div>
</div>
```
_participants_fields.html.erb
```
<div class="nested-fields">
  <%= f.input :first_name, label: "Enter your friend's first name" %>
  <%= f.input :salary, label: "Enter his/her monthly pay" %>
  <div class="links">
    <%= link_to_remove_association "Remove this friend", f , class: "btn btn-danger btn-xs" %>
  </div>
</div>
```

events_controller.rb
```
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_event)
    if @event.save

      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def params_event
    params
      .require(:event).permit(:name,:total_price, participants_attributes: [:first_name, :salary, :_destroy ] )
  end
end
```

**Comment by nathanvda** [comment]
What is exactly the problem: the form does not submit, aka sends no data to the server? That might be a problem with your routes. 

It does submit data but it is not saved? If you are on rails 5, you need to take care, since `belongs_to` relations are by default no longer optional, upon validation time (before saving) the event of the participant does not exist yet, so validation will fail, unless you either 1) declare the `belongs_to` as optional, or better 2) declare the `inverse_of` the `has_many` so rails can check the presence/relation correctly upon validation.

So in your case that should probably (you did not include your model/association definitions, so I am guessing a bit) look like: 

           has_many :participants, inverse_of: :event 

If your associations are defined correctly, please show me what is submitted to the server (you can find that in the logfile). 

Anyway, in the `params_event`, in the `participants_attributes` you are missing the `:id` (this will not affect saving, but deleting later on).

**Comment by knopfler81** [comment]
Very nice guess... I missed  `has_many :participants, inverse_of: :event `
Sorry for this ! But Thanks a lot !

**Comment by nathanvda** [comment]
No problem, it is new and I only recently updated the documentation accordingly. Always happy to help :+1: :smile:
