### ISSUE TITLE
Adding one form from start before clicking on Add New

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#420]
First of all, Great gem. I always use it through out all my projects 🥇 

As of today, user needs to click on **Add New** to add a `form` when they *enter* the page.
How can I already have one form ready to fill-out when they enter the page and then they can click on **Add New** for add more.

Thanks in advanced!

**Comment by nathanvda** [comment]
Ok, not entirely clear to me. Do you mean something like hiding a div and showing it when they click a button, or do you mean showing a modal when they click a button, or do you mean following a link to a form on a  new page? (which are all pretty obvious and not really related to cocoon). 

The user visits a page, sees the `Add New` button, clicks it and is taken to the form???? So a simple `= link_to 'Add new', new_person_page, class: 'btn btn-default'` right?  

So that is probably not it, so what do you mean? Please explain it in more detail. Or you want a page to allow your users to add more than 1 at a time of a certain thing (_when you do not explain your question in detail I get to give these horribly abstract answers_) without an association? See #222, #220, #248 ...

**Comment by Rubioli** [comment]
Thanks for reply and sorry for misunderstanding.

What I meant was that, currently I have 2 models `Post` & `Slides` & I have `accepts_nested_attributes_for :slides, reject_if: :all_blank, allow_destroy: true`.

So when user goes to `posts#new` action to create a post & add slides, they need to click on `= link_to_add_association "add slide", f, :slides` for adding the form where they can add a slide.

What I am asking is if its possible to have 1 `form/nested_form` for adding slides ready when user comes to `posts#new` *(without needing to click on `link_to_add_association`)* and if user want to add more then one slide then can click on `link_to_add_association`.

Hope I am more clear this time :)

Thanks in advanced!

**Comment by nathanvda** [comment]
Ah, that is clear! That is actually pretty easy: in your controller, in the `new` action you can just pre-create one slide. So in code, in the simplest version, this looks like: 

    def new
      @post = Post.new
      @post.slides.build 
    end

**Comment by Rubioli** [comment]
Your the man 🥇  Oh man, really again, Thank a bunch for your gem. Don't know wha would I do without it 💯

**Comment by iraszl** [comment]
Great gem and tip!

If at least one element (Task) is required in the form, the first "Remove Task" button doesn't make sense. How best to remove it.

**Comment by nathanvda** [comment]
Hi @iraszl please open a new issue for this question.

**Comment by iraszl** [comment]
I found the answer here in case somebody else needs it: https://github.com/nathanvda/cocoon/issues/430 Thank you for your attention.
