### ISSUE TITLE
Rails 5.1 compatibility

### ISSUE THREAD

**Issue by peracchi** [nathanvda/cocoon#423]
Hi @nathanvda !

I am trying to use cocoon with Rails 5.1 and cannot get it to work.
I still learning, but I think it's related with [ jquery + jquery_ujs ] used up to Rails 5.02 vs [ rails-ujs ] used in Rails 5.1.
Can you please give me some advice on this question?

Best regards!

**Comment by Mirv** [comment]
Hi Peracchi, I'd advise that while you wait on Nathanvda, you check out this section here for trouble shooting the jquery with rails & cocoon ... https://github.com/nathanvda/cocoon/wiki/Trouble-shooting:-Jquery-issues

**Comment by Mirv** [comment]
@peracchi  Just following up - were you able to use the guide to trouble shoot the issue or did you post to stackoverflow yet for general trouble shooting help?

**Comment by peracchi** [comment]
@Mirv I still in the learning process, so for now I go back to Rails 5.02 to get the examples to to work. Thanks for asking! :)

**Comment by Mirv** [comment]
If you open a stackoverflow with your exact error & copy of the controller, view's & models I'll take a quick peak & more than likely 5 people will pop up to help too!

**Comment by hanchang** [comment]
I just successfully installed, configured, and integrated cocoon on Rails 5.1 so there doesn't seem to be an issue. Just needed to add jQuery to the application view template before any other JS: `= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"` since Rails 5.1 no longer ships with jQuery installed by default.

Hope that helps!

**Comment by nathanvda** [comment]
Awesome thank you for testing this :+1:
