### ISSUE TITLE
Nested children in modal box with cocoon

### ISSUE THREAD

**Issue by LRP500** [nathanvda/cocoon#426]
Hi !

I'm having a strange problem with Cocoon and I'm not sure yet where it comes from.
But there it is.

I have a dynamically created table in wich each record/row contain an icon to pop a modal. In this modal I would like to add and remove children of the record via Cocoon.

**The modal looks like this:**
_form.html.erb
`<%= render partial: 'spread_fields', locals: { f: c, index: index } %>`

__spread_fields.html.erb
```
<span class="glyphicon glyphicon-cutlery" data-target="#<%= "spreads#{index}" %>" data-toggle="modal"></span>

<div id="<%= "spreads#{index}" %>" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= f.fields_for :spreads do |spread| %>
          <div class="col-lg-3">
            <%= spread.input :start, label: 'Debut'%>
          </div>
          <div class="col-lg-3">
            <%= spread.input :ending, label: 'Fin' %>
          </div>
          <div class="col-lg-3">
            <%= spread.input :percentage, label: '%' %>
          </div>
          <div class="col-lg-3">
            <p align="right"><%= link_to_remove_association 'delete', spread, class: 'btn btn-danger' %></p>
           </div>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'add', f, :spreads, class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Simply adding the link_to_add_association give me really strange error**
`undefined local variable or method 'index' for #<#<Class:0x007fd3f8349b70>:0x007fd3fa345eb0>`
**or**
`Association spreads doesn't exist on Spread`

So my question is, am I supposed to be able to use Cocoon in a modal box ? If I am, is there any peculiar behavior I should be aware of to successfully do this ?

Thanks

**Comment by Mirv** [comment]
One post from Nathan says - might not work depending on the UI techniques to show modal -
 https://github.com/nathanvda/cocoon/issues/216

Other apparently the guy got it working - https://github.com/nathanvda/cocoon/issues/384

**Comment by nathanvda** [comment]
First off, your errors: 

The first error: you use a local `index` so you will have to pass this to in your `link_to_add_association`. Something like `link_to_add_association 'add', f, :spreads, class: 'btn btn-primary', render_options: {locals: {index: index}} 

The second error is a bit harder because you give so little context, I have no idea how your models are associated and what your main form is. But the error seems to suggest your main form-object is `Spread` which does not have an association (seems obvious?). 

Also a bit confused as to when showing a row/grid of parents, where your form is declared, please note that a modal is not rendered "inline", and for a HTML form to work it really has to be enclosed by form statements. What would work perfectly is to have a complete form inside the modal (and only make the children editable/visible for instance).

**Comment by LRP500** [comment]
Thanks for you quick response

Sorry about not giving a lot of context, my form was getting humongously huge... I tried to simplify it here. But good news for me I solved my problem.

Here I gave an answer to my own question if this can help anyone 
http://stackoverflow.com/questions/44065406/rails-cocoon-nested-form-in-modal/44067026#44067026
