### ISSUE TITLE
How to show one (first) nested_fields by default?

### ISSUE THREAD

**Issue by Aravin** [nathanvda/cocoon#429]
How to show one nested_fields by default?

I could not see this feature in any of your document. Do I need to manually add one set of fields in `_form.html.erb`

**Comment by Mirv** [comment]
In the controller you call the rails default method for it.... `.build`  

Example:

```
@burger = Burger.cheese.build
```

**Comment by Aravin** [comment]
@Mirv  No, you didn't get my point, I think.

**Comment by Mirv** [comment]
@Aravin it's not that I did or did not get your point - you aren't providing enough details for people to answer your question.

First:  what are you trying to accomplish?
Second:  what specific page are you working on which would call this thing?
Third:  why is this important?

If you don't provide those things, people can take 15 or 20 minutes of their day to help you create something you only think you want - when in fact there were easier ways that are used by all programmers to do it in 10 seconds.

**Comment by nathanvda** [comment]
@Aravin Please check previous issue which seems related: 

* https://github.com/nathanvda/cocoon/issues/420

So in short: you pre-build a nested item so it is rendered in the form. If this is not your question, instead of claiming "we missed the point", why not try to _explain_ your question better so we might get the point?

**Comment by Aravin** [comment]
Same as #420 @nathanvda  thanks.
