### ISSUE TITLE
Rendering different partials for New & Edit views/actions

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#432]
In my application there are some stuff I want to do with nested forms when they are being added in new record *`new.html.haml / new action`* and some other stuff to them when they are being edited *`edit.html.haml / edit action`*.

Currently both of the forms use same partial `_image_fields.html.haml` & what I wonder about is if I can use different partials for each of them.

For instance I want to render `_new_image_fields.html.haml` in `new.html.haml` & `_edit_image_fields.html.haml` in `edit.html.haml`.

*nb: Im not rendering `_form.html.haml` in `new.html.haml` or `edit.html.haml`*

Appreciate any help :)

**Comment by Mirv** [comment]
Hi Rubioli....

There's nothing I can think of that prevents cocoon gem from working with it.  I've loaded partials dynamically before and all you do is make a helper to decide which partial and in the namespace of the file which has the `render` call.

Side note - Make sure to read the documentation on partials - [Link](https://github.com/nathanvda/cocoon#partial-1) - Since that's the topic at hand.

stackoverflow is where you're going to want to post this one, they have a Q&A along with a design forum, codereview & engineering section.

**Comment by nathanvda** [comment]
Check the [documentation](https://github.com/nathanvda/cocoon#partial), there is an option called `:partial` which allows you to hand `link_to_add_association` any partial you prefer.

E.g. something like 

```
= link_to_add_association 'add image', f, :images,
    partial: 'new_image_fields'
```

**Comment by Rubioli** [comment]
Thanks for your help :) . Sorry I didn't read the docs clearly
