### ISSUE TITLE
README text / jQuery removal?

### ISSUE THREAD

**Issue by whistlerbrk** [nathanvda/cocoon#441]
> This gem depends on jQuery, so it's most useful in a Rails 3 project where you are already using jQuery. Furthermore, I would advise you to use either Formtastic or SimpleForm.

Are you deprecating your own gem with this message? I read that as a "don't use this for greenfield projects" message, but there is nothing else I've found which does what cocoon purports to do.

Yes, I do know jQuery has been removed as a default dep in Rails and I checked out the `cocoon.js` file which at only 131 LOC seems like it could be replaced with vanilla JS if a day of work was put into it.

Would you accept that PR? Also, would you clarify the README message?

**Comment by nathanvda** [comment]
Mmmmmm no, not deprecating, that is just an old part of the README when it was initially written. It works perfectly fine with rails 3/4/5 but it does depend on jquery. 

For the moment it would be very hard to remove that dependency, definitely in a backwards compatible way because when configuring the insertion of a new partial we heavily rely on jquery.

**Comment by whistlerbrk** [comment]
Okay great! Thanks for getting back so quick, heartening to know this project will be around.

**Comment by will-in-wi** [comment]
Sounds like this ticket can be closed.
