### ISSUE TITLE
Can we redefine the check of `reflect_on_association` ?

### ISSUE THREAD

**Issue by ristovskiv** [nathanvda/cocoon#442]
Now I know that 90% of the use cases the form builder object is a model object with its own associations, but sometimes the object may be a simple PORO (form object) and its class does not respond to the `reflect_on_association`
https://github.com/nathanvda/cocoon/blob/master/lib/cocoon/view_helpers.rb#L111
I understand that there is an easy fix for this, but it does require digging into the gem to find out, and although the gem is not huge, my opinion is that we also need to check if the class of the form builder object responds to `reflect_on_association` first as well, and then proceed further.

Also it does make sense to have a method in a form object class that will simulate the association of the model, since `fields_for` actually works with a simple Array as well.
https://apidock.com/rails/ActionView/Helpers/FormHelper/fields_for (see section for `One-to-many`)

We can even extend this to something additional, like passing the method name for building the collection object or something like that...I do hope I am clear enough.

What do you guys think? If you approve I will gladly make a PR.

**Comment by nathanvda** [comment]
An easy improvement would be indeed to write something like 

~~~
  assoc = f.object.class.reflect_on_association(association) if f.object.class.responds_to(:reflect_on_association) 
~~~

That would already fix it, right? 

The second part of your question I do not quite understand: the `fields_for` thing is not actually part of cocoon so however you want to iterate over your array does not really matter. But of course the `fields_for` also helps in getting the naming correct so that params array/hash is built so that rails immediately knows how to save the associations. How this translates when you are using a PORO is actually up to you, since you will not be able to use the default saving mechanism anyway. So how you define your form object class is not in the scope of cocoon, imho, unless I misunderstood you?

**Comment by ristovskiv** [comment]
No no of course that the `fields_for` is not part of `cocoon` , I was only referring to the fact that actually `cocoon` is dependent of it. That is why I mention that we actually need to check if the object's class responds to `reflect_on_association`, but it is up to the class itself to provide that collection either through an association or a custom method.

Also I what I had in mind about the second part is that either we provide the option of passing the custom method name that will have the responsibility to build the object, or to update the readme which will explain this https://github.com/nathanvda/cocoon/blob/master/lib/cocoon/view_helpers.rb#L122-L126
Which practically requires custom methods to be defined on the object's class itself.

Btw the fix also may be something like this
`assoc = f.object.class.respond_to?(:reflect_on_association) && f.object.class.reflect_on_association(association)`

**Comment by nathanvda** [comment]
Please also note PR #223, where this was already discussed in detail, which I am still reluctant to merge, precisely because of the lack of documentation and the whole setup one would need to provide (your own form objects/saving forms/...) which are completely out of the scope of cocoon. I prefer to keep cocoon simple and to the point, namely help in providing nested forms in rails for activerecord models (where most of the work is done by rails itself of course).

**Comment by ristovskiv** [comment]
Ok that PR actually solves this issue that I've opened, hmmm, I guess it is up to you, and if it's about documentation I wouldn't mind expanding on that as well if you need to.

Btw I know that this is completely unrelated to this issue, and I would understand if you don't want to answer it, but would you mind explaining me why is a check if the build object is frozen here?
https://github.com/nathanvda/cocoon/commit/c545e3df94f19fa15700925ef86eea57bcbb328d

I'm really trying to get my head around this and I can't find an example/case for this.

**Comment by nathanvda** [comment]
Was the commit message (you link to) not self-explanatory? The original discussion leading to that commit can be found here: #193

In short: we build an object on the collection (so we automatically get all the correct defaults and blocks executed if present), and then immediately delete it, so you can still correctly iterate over the collection. However rails will then freeze the object if it was a `belongs_to` relation. In general cocoon is not the best fit for `belongs_to` relation-ships imho (because since recent versions building an object on a `belongs_to`-relation will already destroy existing ones ---bummmmerrrr).

**Comment by ristovskiv** [comment]
Thanks a lot really!
Ok I was stupid enough to be narrow minded and to just think that you will use `cocoon` helpers just for creating/editing a model with `has_one` and `has_many` associations...It really didn't come to my mind of a scenario when you use the helpers for a model with `belongs_to` association.
