### ISSUE TITLE
link_to_add_association disappears if validating and all nested fields have been removed

### ISSUE THREAD

**Issue by JarLowrey** [nathanvda/cocoon#449]
I have an Exercise model that has_many Workouts. Exercise `validates :workouts, presence: true` in the model. If you go to Exercise's `new` form, remove all workouts, and submit, the page will refresh and `Workouts can't be blank` error will be displayed in the form. All good. However, on this new page all Workout inputs, link_to_add_association, link_to_remove_association are gone. It may be a bug in this gem. Any ideas?

**Comment by nathanvda** [comment]
Please show me your view code.

I am guessing you show the `link_to_add_association` in the partial, instead of outside? Also, by default if items are deleted before validation, and validation fails, deleted (or to be deleted items) are hidden, this might not be what you want/expect (especially in this case). Do you see any items in the html? (using inspect?). If not it is a problem in your controller/models?

Validation like that is hard, ideally you hide the `link_to_remove_association` when only one `Workout` is visible (using javascript).

**Comment by JarLowrey** [comment]
I lied a little bit to simplify. I have an event model which has_many workouts. Each workout belongs_to an exercise and an event. Here is the event and workout forms. Exercise is selected using :exercise_name.

view/events/_form.html.erb

```
<%= simple_form_for @event, validate: true do |f| %>
  <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :start %>

  <div>
    <%= f.simple_fields_for :workouts, validate: true do |workout| %>
      <%= render partial: 'shared/workout/form', locals: {f: workout} %>
      <%= link_to_add_association 'add workout', f, :workouts, partial: 'shared/workout/form' %>
    <% end %>
  </div>
  
  <%= f.button :submit %>
<% end %>
```

views/shared/workout/form:

```
<div class="nested-fields" >
    <%= f.input :distance %>
    <%= f.input :duration %>
    <%= f.input :exercise_name, input_html: { data: {autocomplete_source: search_for_named_exercises_path } } %>
    <%= link_to_remove_association "remove workout", f %>
</div>
```

The idea about hiding the `link_to_remove_association` is a great one, here's a working solution using ERB (thus avoiding messy JS complications):

view/events/_form.html.erb

```
<%= simple_form_for @event, validate: true do |f| %>
  ...
  <div>
    <%= f.simple_fields_for :workouts, validate: true do |workout| %>
      <%= render partial: 'shared/workout/form', locals: {f: workout, show_remove: false} %>
      <%= link_to_add_association 'add workout', f, :workouts, partial: 'shared/workout/form' %>
    <% end %>
  </div>
  
  <%= f.button :submit %>
<% end %>
```

views/shared/workout/form:

```
<% show_remove = true if not defined? show_remove or show_remove == nil %>

<div class="nested-fields" >
    ...
    <% if show_remove %>
        <%= link_to_remove_association "remove workout", f %>
    <% end %>
</div>
```

This is a great solution for usability. Thanks!

**Comment by JarLowrey** [comment]
I guess that technically my solution would be a workaround, should the issue be closed or remain open?

**Comment by nathanvda** [comment]
At the moment I think there is not anything I can do, because you say that the `simple_fields_for` is just not present. If there are no nested items, then cocoon is not doing anything wrong :+1: (not hiding to be deleted items for instance).

Normally a failing validation like that should not _really_ delete the nested items (e.g. have an effect on the database).

But great that the work-around works for you!

**Comment by JarLowrey** [comment]
Not sure what I changed, but it seems to be working now. That leads me to believe it was a problem with me, instead of the gem. I removed my fancy partial stuff (since it was causing `link_to_remove_association` to disappear after failed validations) and it still is working fine. IDK
