### ISSUE TITLE
For discussion: $.data() vs $.attr() when querying link_to_add_association data attributes

### ISSUE THREAD

**Issue by dylanfisher** [nathanvda/cocoon#450]
Curious if you have a reason for using `data()` when referring to the association insertion options, rather than `attr()`. https://github.com/nathanvda/cocoon/blob/65eaf1b8028c1236741c15004144a59d77267351/app/assets/javascripts/cocoon.js#L43-L48

I ask because I ran into a little issue that wasn't immediately obvious to debug. I change where cocoon inserts data based on where the user is clicking by modifying the add fields button's data-association-insertion-node attribute.

```js
$(document).on('click', '.insert-field', function() {
  $(this).attr('data-insertion-target', true);
  $cocoonButton.attr('data-association-insertion-node', '[data-insertion-target]');
  $cocoonButton.trigger('click');
  $(this).removeAttr('data-insertion-target');
  $cocoonButton.removeAttr('data-association-insertion-node');
});
```

However, the next time I click on the actual cocoon button it can't find the insertion node because `$addFieldsButton.data('association-insertion-node')` still exists as `data`, even though the attribute no longer exists.

If I remove the attribute and the internal data, it works as expected:

```
$cocoonButton.removeAttr('data-association-insertion-node')
             .removeData('association-insertion-node');
```

So... my question is why use `data()` if these options are dependent on data-attributes specified in the DOM? It may be more appropriate to use `$this.attr('association-insertion-node')` when assigning the association options.

In any case, thanks for the plugin!

**Comment by nathanvda** [comment]
Two remarks: 

* data attributes clearly indicate they contain "extra" data and it is a kind of convention to allow storing/adding extra data, imho? 
* the jquery `$().data` is indeed a pain, it has bitten a few times before as it assumes the `data-*` fields to be read-only. This is probably for efficiency reasons? 

So it is probably a valid argument to use `.attr` instead of `.data` (a little more work to write it, but would make the code a little more robust as well). 

I understand you also already had a workaround. But if you are still interested in creating a PR, I am more than willing to merge it.

**Comment by dylanfisher** [comment]
I agree it makes sense to use `.attr` instead of `.data` if no additional data is being stored, but I worry about changing the way the plugin handles this as it could have breaking consequences if someone did use the "extra" data in some way. For example, if the problem had been the other way around (using `.attr` instead of `.data`) and it was changed, my code would have stopped working. 

Perhaps we can close this comment and the paper trail is enough in case anyone else stumbles on this issue.

**Comment by nathanvda** [comment]
That sounds like a good idea 😉 :+1:
