### ISSUE TITLE
Nested dynamic forms?

### ISSUE THREAD

**Issue by AleFons** [nathanvda/cocoon#463]
I have a form representing a group of products, each with its category, name and price. Currently, I have some partial fields made using cocoon to add new products; each nested field contains the product - selected from a dropdown - and then the price has to be filled manually. I would like to have first a select for the category which filters the product dropdown and then when a product is selected, it fills the price field; while I know how to do dynamic selects like this with javascript, I'm unsure how to get the right element in this case.

**Comment by Mirv** [comment]
hi Ale...you're going to get faster replies on the stackoverflow.com troubleshooting the div name's you made in your project!  Be sure to give examples of your view partials & currently written jquery when you make your post...you can post a link to it back here.

This forum on github is actually for bugs & contributions, not trouble shooting - though it does happen...so you could also try searching previously closed tickets.

**Comment by nathanvda** [comment]
Hi @AleFons, yes please ask this question on stackoverflow.com as it is imho a pure rails/javascript question. If you link the question here I can always take a look. Also please include some view-code of what you tried already, because it is easier to get replies if you showed what you have already done (so people can extend on what you have tried).
