### ISSUE TITLE
Only removing one association at a time

### ISSUE THREAD

**Issue by Joel-Mercier** [nathanvda/cocoon#481]
Hi there, I've been using this gem on a project where multiple files can be uploaded in a step-by-step form.
I don't recall having this behavior a few month ago when this was pushed into production but whenever I try to delete multiple associations (files), only one is actually destroyed on submit and I have to submit the form once for each.
My guess is that the markup for the _destroy field is not correctly being generated because I have this in my HTML for each link_to_remove_association : 
`<input type="hidden" name="admission_file[custom_field_values_attributes][0][_destroy]" id="admission_file_custom_field_values_attributes_0__destroy" value="false">`
It should be 0, then 1, then 2, etc... right ?
I've correctly permitted the id and _destroy attributes in my params.
Any ideas ? Cocoon version is the latest 1.2.11 & rails version is 4.2.7.1

**Comment by nathanvda** [comment]
Are you sure the `[0]` is repeated? Because then you would always delete the first item, right? It is not right, but I have no idea how that would be possible, because the `0` should either reflect the database id of the item, or a random number generated by cocoon when generating a new item.

It reminds me of a mixup between html id's and classes. If you use an html `id` in a repeating field, only the first will be picked up (since id's in html are supposed to be unique). 

But anyway, I am just guessing. Show me some view-code so I can say something more sensible.

**Comment by Joel-Mercier** [comment]
Thanks for the quick reply :) 
Nevermind I found the source of my issue I'm falsely looping over simple_fields_for and my _fields partial, the form builder I built for this website is rather complex.
The joys of opening an old code base again !
Thank you for your time ! You can close this issue
