### ISSUE TITLE
Conditional nested form with two associations problems after presence validation 

### ISSUE THREAD

**Issue by dgbtech** [nathanvda/cocoon#484]
I have a form that have diferent fields depending in one of them. and in my solution I have twice:

```
f.simple_fields_for :attachments do |attachment|
render 'attachment_fields', f: attachment

 link_to_add_association 'add_attachment', f, :attachments
```

And a link to remove in the partial.
Everithing works great but when you add an attachment, its required presence, and if its left blank, after validation error, input apears twice, and I only added it once. So like the other field is hidden I cant send the form.
How can I do to have only one input after validation?

**Comment by nathanvda** [comment]
This depends on your validations, how your association is specified and if you pre-build an empty item in your controller or view (which could explain why you get an extra item). 

So can you show us some more code?

**Comment by dgbtech** [comment]
In mail model:->accepts_nested_attributes_for :attachments
In attachments model->  belongs_to :mail, inverse_of: :attachments
                             validates :file, presence: true

In my view I have twice the code I posted before, and I show it in diferent tabs, sorry I cant post all code, I thought I was missing something obvius. I understand if cant help me ;)

**Comment by nathanvda** [comment]
(no need to paste _all_ the code, just enough to help me understand, if you are stuck create a more generic case to replicate the effect so I can help you).

Also: you should learn about code-formatting in github, so you can just copy the code. In your original post is an error (using `attachment` in your `simple_fields_for` and referring to `notif_attachment` which is not defined) (this is probably a typo, but I have to "guess" all that?)

Anyway, in your `Mail` model you should at least write the following: 

     accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

To make sure blank attachments are simply rejects (and allow destroying since you also show the remove link).

**Comment by nathanvda** [comment]
Closed due to inactivity.
