### ISSUE TITLE
How to generate unique id for has_one association?

### ISSUE THREAD

**Issue by brunohkbx** [nathanvda/cocoon#485]
I have the following association:

A Product has_one ProductTax

```
class CreateProductTaxes < ActiveRecord::Migration[5.1]
  def change
    create_table :product_taxes do |t|
      t.references :product, index: true, null: false
      t.jsonb :icms
      t.jsonb :ipi
      t.jsonb :pis_cofins

      t.timestamps
    end
  end
end
```

I'm trying to use cocoon to create this dynamic field for Icms.
![icms](https://user-images.githubusercontent.com/6487206/35751338-395ce33c-083f-11e8-888c-d676d4fa1b3d.png)

Is it possible to generate a unique ID in this has_one association? Maybe using the before-insert callback.
I need this ID to distinguish the submitted values.

**Comment by nathanvda** [comment]
I do not understand this question. Do you need a html-id? Why do you need the id and what would you do with it? It is a bit unclear what you are trying to do, but if a product has only one product-tax, and you want to manipulate in some way, there is only one to find, right? 

And if you need, for some reason, the database id before it is being saved, that is a bit weird and maybe you should not be using cocoon. Because cocoon just helps in building a form to save everything in one go.

Please explain more to be of better help.

**Comment by nathanvda** [comment]
Closed due to inactivity.
