### ISSUE TITLE
Autocomplete is not working

### ISSUE THREAD

**Issue by sonq** [nathanvda/cocoon#502]
Hey Guys, 

It has been 3 days since i am working on auto complete fields on cocoon. Completions works fine on the parent form however does not work int the child form. 

This is the model of the nested form

```
class Programline < ApplicationRecord
 belongs_to :program, inverse_of: :programlines
 belongs_to :exercise


 def exercise_name
  exercise.try(:exe_desc)
 end

  def exercise_name=(exe_desc)
   self.exercise = Exercise.find_by_exe_desc(exe_desc) if 
   exe_desc.present?
 end

end
```

This is the text field that i want to generate autocomplitions. (note that list comes to the html however it just does not show up when i start writing an element which exist in the list)

```
<%= f.text_field :exercise_name, data: {autocomplete_source: Exercise.order(:exe_desc).map(&:exe_desc)} ,class: "form-control", placeholder: "Exercise", autofocus: true %>
```

and finally this is the programline.js file

```
     jQuery ->
     $(function() {
      $(document).on("focus","programline_exercise_name", function() {
        $('programline_exercise_name').autocomplete({
            source: $('programline_exercise_name').data('autocomplete- source')
              }); 
                });
                  })
```

**Comment by nathanvda** [comment]
If you post this on the cocoon page, I am assuming the `text_field` is dynamically inserted into the page using cocoon `link_to_add_association`. This would suggest you would need to be using [callbacks](https://github.com/nathanvda/cocoon#callbacks-upon-insert-and-remove-of-items) to enable the autocomplete on the dynamically added fields. Because none of the fields are in the page when you initially run the javascript.

But your js shown uses `$(document).on` so that would already work. _However_ your code is incomplete or for demonstration purposes, but your selection filter for jquery seems wrong. You write `on("focus","programline_exercise_name"` and `$('programline_exercise_name')` which would go looking for a html-element with that name. Like `$('p')` will select all paragraphs. I am assuming you want to select an element with id or class `programline_exercise_name` ? For dynamically added fields you would definitely be using a class, but then your jquery snippet would also be wrong. 

So if you the wanted class-name to the field

```
<%= f.text_field :exercise_name, data: { autocomplete_source: Exercise.order(:exe_desc).map(&:exe_desc)},
      class: "form-control programline_exercise_name", 
      placeholder: "Exercise", 
      autofocus: true %>
```

You would then need something like

```
$(document).on("focus", ".programline_exercise_name", function() {
        var _this = $(this); 
        _this.autocomplete({
            source: _this.data('autocomplete- source')
        }); 
      });
})

Not tested, so let me explain: when the `focus` event is triggered on any of the `programline_exercise_name`, only set the autocomplete for the element that caused the event.

**Comment by nathanvda** [comment]
The OP also asked this question on stackoverflow where I posted the same [answer](https://stackoverflow.com/questions/50267050/autocompletion-in-a-nested-form-text-field/50274169) which was accepted.

**Comment by sonq** [comment]
For the one who try to achieve using autocompletion with cocoon, solution is to create controller for the nested fields which should be subclass of parent form. Do not change the parent controller, but make your modifications related to autocompletion on nested form controller. 

But if you will try to use save autocompletion on multiplefields, autocompletion will use always the first field of the nested form. I will try to solve this out, if i can i will post it here if i wont i will open up a new issue.

**Comment by nathanvda** [comment]
Which gem are you using for the autocomplete? I do not understand why you should be adding a controller for the nested fields??? As a subclass of the parent controller? I do not understand: did the original solution not work? Or are you now trying to get a list of possible values from a controller end-point instead of filling them in hard-coded (what you did before).

**Comment by sonq** [comment]
Hey nathanvda,

I use [rails-jquery-autocomplete ](https://github.com/risuiowa/rails-jquery-autocomplete) .

If you will check the documentation, we need to make some modifications on the controller. But as i use cocoon and cocoon uses controller of the parent form, i needed to create a new controller. Because, implementing the autocompletion related code in my parent form controller did not work. 

So this is my main controller: 

`class ProductsController < ApplicationController 


before_action :set_product, only: [:edit,:update,:show,:destroy]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :authenticate_user!


  

  def new
  
    @product = Product.new

  end


      def create

        @product = Product.new(product_params)
        @product.user = current_user
       
        
        if current_user.dataoperator? 
          @product.type_id = 1  #System defined product type
        elsif current_user.admin?
          @product.type_id = 1 #System defined product type
        else
          @product.type_id = 2 #User defined product type

        end

 
          if @product.save
            #do something
            flash[:success] = "Product has been added!"
            redirect_to products_path
          else
            #flash[:danger] = "Try again!"
            render 'new'
          end


      end



  def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:success] = "Sucessfully updated."
        redirect_to products_path
      else
        render 'edit'
      end
  end





   def edit
  
      @product = Product.find(params[:id])

   end

  def index

    @products = Product.where(["user_id = :user_id OR type_id = :type_id  ", {user_id: current_user,  type_id: 1}])

  end








    def show

      @product = Product.find(params[:id])

    end



    def destroy

    @product.destroy
    flash[:danger] = "Procut is deleted."
    redirect_to products_path


    end




  private

  def set_product

    @product = Product.find(params[:id])


  end


  
  def product_params
        params.require(:product).permit(:pro_desc,
                                        :pro_directions,
                                        :type_id, 
                                        :user_id,
                                       productlines_attributes: [:id,:prl_desc,:calorie_id,:product_id,:prl_calories,:prl_protein,:prl_totalcarbs,:prl_fat,:prl_quantity,:prl_grams,:_destroy]
                                        )
  end



  def require_same_user 
    if current_user != @product.user and !current_user.admin? and !current_user.dataoperator? 
      flash[:danger] = "You can edit only your records"
      redirect_to products_path
    end
  end



end`


And this is the controller that i had created for cocoon: 
`class ProductlinesController < ProductsController 



  autocomplete  :calorie, :cal_desc , :extra_data => [:cal_protein,:cal_calories,:cal_totalcarbs,:cal_totalfat],:display_value => :funky_method



  def protein_element

    

  end










end`

**Comment by sonq** [comment]
Hey nathanvda,

i use rails-jquery-autocomplete 
And if you check the documentation, it needs to use controller. However, for my cocoon fields i did not have anycontroller so i needed to create one like this:

`
class ProductlinesController < ProductsController 
  autocomplete  :calorie, :cal_desc , :extra_data => [:cal_protein,:cal_calories,:cal_totalcarbs,:cal_totalfat],:display_value => :funky_method
end
`

**Comment by sonq** [comment]
Nathanvda,

Also please see the bellow video to understand my current problem better. 
https://drive.google.com/file/d/1Z48ZL4luKYmYLmwuBwvYuhVTsdnIPIaD/view?usp=sharing

**Comment by nathanvda** [comment]
I am not sure why you think showing me a video is more helpful than showing me some code or _use your words_. 

Also not sure why you reuse a closed issue, which was solved, right? This is a completely new problem, right? You have some javascript code that fills in the id and that is not working now? Please open a  new issue for this specific problem please or ask this on stackoverflow and post the url to the question here, since this seems to be a general javascript problem. You will have to use the callbacks to make sure the javascript to fill in the id is also activated on the newly/dynamically inserted html (as before).
