### ISSUE TITLE
Compatibility with jquery 3.x ?

### ISSUE THREAD

**Issue by kevinhq** [nathanvda/cocoon#514]
Hello,

We're upgrading to jQuery 3.x from jQuery 1.12.

We got a warning about: `JQMIGRATE: 'ready' event is deprecated`

And it's coming from this codes:

`$(document).on("ready page:load turbolinks:load", function()`

We already used  1.2.11 which is the latest version of cocoon.

Any plan to do update on this to make it fully compatible with jquery 3.x without warning?

**Comment by nathanvda** [comment]
I have a plan to update that indeed to a more robust/generic version. However, in the code there will still be a mention of the "ready" event depending on your jquery version, so your migrate process (jqmigrate?) might still give a warning. 

At this time this code works with jquery 3, as long as you use turbolinks, since the `turbolinks:load` is also triggered on ready.
