### ISSUE TITLE
Is there a way around avoiding a n + 1 type situation with rendering the cocoon partial?

### ISSUE THREAD

**Issue by Lee1984** [nathanvda/cocoon#517]
Say, I have a post and it has a comment form and it uses cocoon partial insertion but that post and form is rendered 15 times per page, say so a user can respond to that post and upload pictures to their comment. 
This is only a problem for ajax calls, normal html calls render almost instantly. 
While rails performs the sql and cocoon grabs that partial for each call this is extremely slow, especially when you also have 'shared/error_messages' partial as well.. It takes about 6 - 7 seconds.

Is there any sound way of using a pre-existing partial or loading only one partial on the page and getting insertion behavior from that?

I would really like to know.

**Comment by Lee1984** [comment]
I may have a way around this if I create my own link to add association and pull the data-association-insertion-template from another form on the page then I should be able to use that partial and my link_to_remove_association should work  from the cocoon.js on the page

**Comment by nathanvda** [comment]
You do understand it is pretty nearly impossible for me to say anything useful without you showing any code. I do not understand the html vs ajax difference. 

I do not understand why it should 6-7 seconds (without more code/explanation). 

Except the obvious: rendering 15 link_to_add_associations will render your partial 15 times, indeed. I do not understand why it would take so long, again (without seeing any code). And definitely rendering the `shared/error_messages` could not take any time since you are inserting a new item without validation errors, right? Again: maybe I am overly optimistic here, since you did not show my any code.

**Comment by Lee1984** [comment]
No, I was being overly optimistic. After I posted this I went through the link_to_add_association in the gem and the cocoon.js and realized there would be no obvious way to do what I wanted only perhaps putting one instance of the partial on the page and using that with some jquery.

I posted on SO about the speed issue between ajax and HTML calls.

**Comment by nathanvda** [comment]
Closing. Without a link to SO question, or any code, I do not understand what OP would still expect to happen here.
