### ISSUE TITLE
How to add an intermediary object that sits between the partial's model and the form's model 

### ISSUE THREAD

**Issue by srinitude** [nathanvda/cocoon#528]
I'm trying to create a nested form, where the model of that partial is actually related to the parent form's model through an intermediary object (e.g. A User has many Profiles through a UserProfile and a Profile belongs to the UserProfile). Is there any existing way to accommodate this in Cocoon, @nathanvda? I want to be able to create the intermediary object (i.e. the UserProfile) when I'm creating the model for the partial (i.e. Profile)

**Comment by nathanvda** [comment]
In most cases, where there is a simple join model, rails will automatically handle the creation for you. E.g. in your example just create profiles through the form and rails will create the user-profiles automatically.

Alternatively, if your `UserProfile` has some extra fields, you could create the user-profile with the nested profile in one go as well. 

Also, if you are using a `UserProfile` table, I am assuming a user could have many profiles, and the profiles would be shared, e.g. some kind of 'role', so it would be fixed? So in that case I would do something like add a small nested form where I show a drop-down to select the profile and then maybe allow an option to create a new if it does not exist yet. 

You can check the [guide to doing nested model forms](https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms) or the [example project](https://github.com/nathanvda/cocoon_simple_form_demo) where this is demonstrated.

I am guessing this is a theoretical question (did you already try something out?), but it is more helpful if you now proceed coding, and when you got stuck, show some code so I can help you a little more specifically.

Was that helpful? Is anything not clear?

**Comment by srinitude** [comment]
Definitely clear, but I should probably better lay out my example and obfuscate it a little bit since I'm working on a proprietary codebase. Here are the relationships:

```
class Profile
  has_many :profile_sections
  has_many :resources, through: :profile_sections
  has_many :profile_requirements, through: :profile_sections
end

class ProfileSection
  belongs_to :profile
  has_many :resources
  has_many :profile_requirements
end

class Resource
  belongs_to :profile_section
  belongs_to :profile, through: :profile_section # There's no through, but trying to create association
end

class ProfileRequirement
  belongs_to :profile_section
  belongs_to :profile, through: :profile_section # There's no through, but trying to create association
end
```

When I try to create the `Profile` through the nested form, I get this validation error:
`Profile requirements profile section can't be blank`

**Comment by nathanvda** [comment]
Not sure if that is the error, but you seem to have omitted the `inverse_of:` option on the `has_many` associations which helps rails in deciding how to build the relations? (or just omitted for brevity?)

As explained in the cocoon documentation, since rails 5 a `belongs_to` relation is `required`, which means it will not save if the referring id is not filled in, however when editing nested forms, OF COURSE we do not know the id because we are creating them. So rails has to be told how the relations relate to each other. (Aaargghhh struggling to explain that clearly, I hope I made that clearer instead of harder to understand).    

If you do have the correct `inverse_of` could you please show your view code to see how the form is build? Or show me the parameters posted to the controller (which you can find in the logfile).

**Comment by srinitude** [comment]
Embarrassed to say that I haven't used or heard of `inverse_of:` until right now! We're currently using Rails 4, but I'll read the guides and give that a try. Thanks so much for your patience @nathanvda :)

**Comment by nathanvda** [comment]
Closed due to inactivity (and asssuming it worked :smile: )
