### ISSUE TITLE
Autocomplete with cocoon on multiple columns

### ISSUE THREAD

**Issue by sonq** [nathanvda/cocoon#531]
I have problem with my cocoon fields which; i can pull the data required from the foreign table for the first nested field. However, when i add the second field and type to pull data for that field, it basically pulls the data without problem but it inserts it to the first field. 

This is my view for the cocoon: 

```
<div class = "nested-fields">
   <div> 
   <%= f.label 'Food ' %>


  <%= f.text_field :calorie_id, :id => "id_element" %>
  <%= f.text_field :prl_protein, :id => "protein_element" %>
 

  <%= f.autocomplete_field :prl_desc, autocomplete_calorie_cal_desc_productlines_path ,  
  :update_elements => {:id => "#id_element", :cal_protein => "#protein_element" }  %>

  
</div>      
   <%= link_to_remove_association "Remove", f %>
</div>
```

And this is my controller for the cocoon:

```
class ProductlinesController < ProductsController 

      autocomplete  :calorie, :cal_desc , :extra_data => [:cal_protein,:cal_calories,:cal_totalcarbs,:cal_totalfat,:id]
      

end
```
I think what autocompletion does is, finding the first fields with id_element and protein_element and put the data in them. What i believe is, if i can put the new lines above of the old line my problem is going to be solved but i dont know if i am wrong or right because i couldnt find out how to put new fields on the first line.

Any help will be appreciated,
Thanks in advance!

**Comment by sonq** [comment]
nathanvda, i am using 'rails-jquery-autocomplete' gem. 

Is there a any way to add new cocoon line on top of the old line? i think this might be the solution.

**Comment by nathanvda** [comment]
While this might work visually, once you post the form to the server, it will fail. Remember: an element with a given id is supposed to be unique and so when posting a form, elements with the same id will be removed (only one value/set will be retained). So this will not work. 

Not sure how you can easily solve this using the `autocomplete_field`, afaik the `update_elements` requires an id, so that would not work in this case (well checking the docs: it requires a selector, so it does not have to be a id of a single element, it could be something like `#nested-child-x .protein_element` but that is also hard). 

They do have a callback which would allow you to maybe handle this yourself? I see two options: use the autocomplete callback to set the fields, or use the cocoon callback to set a more precise/correct selector --although that imho seems the hardest solution. 

In any case, imho not sure how I can help here. This seems more like a autocomplete or javascript problem? Maybe best ask on stackoverflow or the `rails-jquery-autocomplete` issues.

**Comment by sonq** [comment]
okay nathanvda, thank you for your time!

**Comment by nathanvda** [comment]
No problem, good luck :+1:
