### ISSUE TITLE
Show button to another page

### ISSUE THREAD

**Issue by sonq** [nathanvda/cocoon#546]
Hello,

My nested form is working perfectly in a table. I would like to add show button which will direct user to another show page. (belongs_to and has_many associations have been built)

Right now  i am trying to use this:

`<td> <%= link_to 'Show', product_path(:id=>(f.product_id)), class: "btn btn-outline-success", target: :_blank %> </td>  `

but getting this error:

> undefined method `product_id' for #<ActionView::Helpers::FormBuilder:0x00007fa4d96fc4a0>

Any help will be appreciated!

Regards

**Comment by nathanvda** [comment]
So the `f` points to the `FormBuilder` as the error indicates. To reach the object that is being "built" you have to use `f.object`. So in your case `f.object.product_id` should work.

**Comment by sonq** [comment]
Thanks nathanvda, i think should work as well but did not :) 

it started to give this error:
> No route matches {:action=>"show", :controller=>"products", :id=>nil}, missing required keys: [:id]

when i tried it with index page instead of show it generated this url
http://localhost:3000/products.98

so i think it generates "." instead of "/".

Do you have any idea how i can solve this out?

**Comment by nathanvda** [comment]
Hey let me debug your code without actually seeing anything of it, and having no clue of any context of it. 

But to state the obvious: 

* the `product_id` is actually set? (like, before save is it set? when adding a new item?) 

You could try writing it like `product_path(f.object.product)` but `product_path(id: f.object.product_id)` should be correct, which means the `product_id`  is really nil imho. Which also could make sense if is not yet filled in when rendering the form (because the new item that has to be inserted is rendered before hand --but a lot of assumptions here as I have no idea what the product-id is, points to, is it the parent, should it be selected, how is it filled  in?). 

You probably need to either: 

* if you know the product-id for some reason, fill it in with the `wrap-object` option (allows you to initialise some stuff before rendering the partial). See https://github.com/nathanvda/cocoon#wrap_object 
* or show the link conditionally (only when it is set), because it still has to be selected or filled in later ...

If, for some crazy reason (like have no context and no idea what your context/code actually is) this does not help you at all and is not relevant, please either give me more  context and information, or please ask this question on stackoverflow (and post the link here if you want).

**Comment by sonq** [comment]
Hey nathanvda,

i have posted a question on stack with. here is the link
https://stackoverflow.com/questions/55530517/show-button-to-another-page-using-cocoon-gem

**Comment by nathanvda** [comment]
Closed, question moved to stackoverflow.
