### ISSUE TITLE
Cannot add link_to_add_association in partial file

### ISSUE THREAD

**Issue by nitinbarai777** [nathanvda/cocoon#549]
![Screenshot from 2019-05-13 12-29-51](https://user-images.githubusercontent.com/1825726/57601777-0feb0b00-757b-11e9-9c4c-0e3f303a7d93.png)
![Screenshot from 2019-05-13 12-30-24](https://user-images.githubusercontent.com/1825726/57601778-0feb0b00-757b-11e9-9f29-e73bb23da71c.png)
![Screenshot from 2019-05-13 12-31-01](https://user-images.githubusercontent.com/1825726/57601779-1083a180-757b-11e9-8b67-b09af88f5dfd.png)

**Comment by nathanvda** [comment]
I hope you got it fixed? The error in the last screenshot seems obvious? Some remarks for future issues: 

- please provide some explanation what you are trying to achieve and what is failing 
- in general: prefer to copy code instead of screenshots (it allows to e.g. copy the code and either test it locally or edit and show you a fix). Also: it is easier to read, to search (for future reference).
- provide model-code (showing the associations) (not the complete code, but just so I can understand it)
