### ISSUE TITLE
Association equipment doesn't exist on Equipment

### ISSUE THREAD

**Issue by silvadavi** [nathanvda/cocoon#572]
Boa tarde minha aplicação está com o erro que está no titlo, é possivel me ajudar? o projeto está no meu gitlab git@gitlab.com:Davu/lts.git

**Comment by nathanvda** [comment]
Hi @silvadavi my name is Nathan Van der Auwera, from Belgium, and my native language is Dutch. The main language on this platform is English, because more people know English, and since I am probably the only one reading and responding to your question, it helps if I can actually read and understand the question. 

Could you please: 1) translate, 2) explain your problem in more detail? Please show me:

* your (simplified) model, especially the associations
* your form-view code

**Comment by silvadavi** [comment]
Good afternoon my application is in "error or does not exist,"can you help me? the project is not on my gitlab git@gitlab.com: Davu / lts.git

**Comment by silvadavi** [comment]
Good afternoon my application is in "error or does not exist,"can you help me? the project is not on my gitlab git@gitlab.com: Davu / lts.git
