### ISSUE TITLE
Markup changes on form error, then on resubmittal field is not saved?

### ISSUE THREAD

**Issue by Lee1984** [nathanvda/cocoon#577]
Hi Nathan,

When there is a error and the form is returned when I correct the error in markup and resubmit the form I get a error;

Markup changes from, after inserting file,

    <input accept="image/jpg,image/jpeg,image/gif,image/png" id="gallery_pictures" type="file" name="gallery[pictures_attributes][1585000567269][picture]">

to, on return,

    <input accept="image/jpg,image/jpeg,image/gif,image/png" id="gallery_pictures" type="file" name="gallery[pictures_attributes][0][picture]">

When I first submit the form the parameters are,

    Parameters: {"feed_value"=>"1", "gallery"=>{"name"=>"", "cover"=>"", "pictures_attributes"=>{"1585000074460"=>{"_destroy"=>"false", "picture"=>#<ActionDispatch::Http::UploadedFile:0x0000000011983e90 
    @tempfile=#<Tempfile:C:/Users/Lee/AppData/Local/Temp/RackMultipart20200324-48196-1t4byji.jpg>, @original_filename="A Perfect World Mix Picture.jpg", @content_type="image/jpeg", 
     @headers="Content-Disposition: form-data; name=\"gallery[pictures_attributes][1585000074460][picture]\"; filename=\"A Perfect World Mix Picture.jpg\"\r\nContent-Type: image/jpeg\r\n">}}}, 
    "commit"=>"Create Gallery", "remotipart_submitted"=>"true", "authenticity_token"=>"/+NoPfx/TpGzpG916GrU2ro6iVosNEdk3nte8V7aLAXJBzdsL91Mu9myMJQ7z2aFTd/o/aqNfyDPHnwv8s/l7Q==", 
    "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01", "all_galleries"=>"cugalleries", "user_id"=>"4"}

then on resubmit they are,

    Parameters: {"feed_value"=>"1", "gallery"=>{"name"=>"hi", "cover"=>"", "pictures_attributes"=>{"0"=>{"_destroy"=>"false"}}}, "commit"=>"Create Gallery", "all_galleries"=>"cugalleries", "user_id"=>"4"}

I am just re-rendering the form on error,

Then on the second save attempt my `picture` attribute saves as nil, as there is no `picture` to save

What could be going on here? Thanks

Lee.

**Comment by nathanvda** [comment]
I can explain why the numbers change. So the normal index is the `id` of the row in the database (logical, that way rails knows which rows to update/delete). Likewise: if the `id` does not exist in the database, rails knows to create a new row.  Cocoon creates an _unexisting_ id when inserting a new row by creating a kind of random number. Upon re-rendering this number is replaced by a more "sensible" number by rails. So imho that is expected behaviour (and also not wrong).

But why you lose your uploaded image, that I cannot explain. This is something not "controlled" by cocoon, that is just standard rails form behaviour, and that should work. 

I would propose asking this specific part of the question on stackoverflow. A question to get you started: https://stackoverflow.com/questions/15680484/how-to-persist-file-upload-fields-after-a-rails-validation-error

**Comment by Lee1984** [comment]
Thanks Nathan.

**Comment by Lee1984** [comment]
I will add, I realized from other form submitals by js that instead of re-rendering the form with errors just render the errors partial, so I did that
