### ISSUE TITLE
Checking whether or not date inputs are 30 days apart after insert is fired off

### ISSUE THREAD

**Issue by RailsCod3rFuture** [nathanvda/cocoon#584]
Greetings, I have a work history form that needs to sequentially be checked for a 30 days gap. I have an input date field called end_date. The field has to be compared with another end_date field after a node is inserted. If there is no 30 day gap, an event is fired off. If there is a gap, then no event is fired off. How can this be done with cocoon:after-insert?

**Comment by nathanvda** [comment]
Hi, thank you for now closing #538 where you never replied on my request for more info. Only to open a new question with too little information for me to help you, and which does not seem overly related to cocoon anyway. 

Please ask this question on stackoverflow. 

You would do it the same way one would do it without using cocoon? This is a pure javascript question where you want to compare two input fields (if I understand correctly). But please remember: comparing "an end_date" with "another end_date" is extremely vague to begin with. Also on stackoverflow you will have to show some code, your view, your attempt to make it work, just to be able to react and correct instead of writing everything myself.

**Comment by nathanvda** [comment]
Closed due to inactivity
