### ISSUE TITLE
Possible security issue allowing id in strong params

### ISSUE THREAD

**Issue by collimarco** [nathanvda/cocoon#588]
I am considering using this gem in a new project.

However I have security concerns about allowing the `id`:

```
  def project_params
    params.require(:project).permit(:name, :description, tasks_attributes: [:id, :description, :done, :_destroy])
  end
```

A malicious user could arbitrarily set the id on a new record...

One of the many things that come to my mind is that you can use ids out of sequence, compared to the auto-increment, thus creating failures in the application when the auto-increment reaches that values and find them to be already present.

I post it here, since I haven't found a better place to report this.

**Comment by nathanvda** [comment]
Are you familiar with how `accepts_nested_attributes_for` works? That is standard rails functionality. So: you can not "set" an id of non-existing item. The `id` field is _obviously_ needed for editing and destroying items. Afaik if the given `id` is not known, it will create a new item and assign a new id (as is customary) (because that is what I do in the frontend: I assign a definitely non-existing id, and rails replaces it with a normal new id).
